### ISSUE TITLE
10.14 Mojave support

### ISSUE THREAD

**Issue by trntv** [Toxblh/MTMR#100]
Hi, is there any roadmap for supporting Mojave?

**Comment by Toxblh** [comment]
16.2 already supported 10.14. Any problems?

**Comment by trntv** [comment]
brew formulae have only 16.1, so I've missed a new release. I'll check it now
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mtmr.rb

**Comment by trntv** [comment]
works fine, thank you

**Comment by Toxblh** [comment]
so I'll update brew cask today
