### ISSUE TITLE
Would you add advanced timeline and Picture-in-Picture icon ?

### ISSUE THREAD

**Issue by mehdi-S** [Toxblh/MTMR#111]
<img width="1085" alt="capture d ecran touch bar 2018-09-08 a 22 10 14" src="https://user-images.githubusercontent.com/7304874/45258189-16a1fc80-b3b4-11e8-88d7-d2b27d622373.png">

Here is a screen shot in safari when watching video stream like youtube or twitch.tv
The center part is a timeline slider and on the right of it, the picture-in-picture toggle icon

more info about PiP : https://support.apple.com/en-us/HT206997

**Comment by Toxblh** [comment]
Try it
```js
{
    "type": "staticButton",
    "title": "⇲",
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"Safari\"\rdo JavaScript \"javascript:var video = document.querySelector('video'); video.webkitSetPresentationMode(video.webkitPresentationMode === 'picture-in-picture' ? 'inline' : 'picture-in-picture');\" in document 1\rend tell"
      // You must enable the 'Allow JavaScript from Apple Events' option in Safari's Develop menu to use 'do JavaScript
    },
    "align": "left",
    "width": 40,
  },
```

**Comment by mehdi-S** [comment]
function well on safari, thanks, since Chrome now allow PiP inside his browser, is this Apple Script updatable to embrace the function inside this two browser ?
https://www.omgubuntu.co.uk/2018/07/enable-google-chrome-picture-in-picture

**Comment by Toxblh** [comment]
You can write one apple script, with check what now already open and also activate PiP

For google you can try it:

```js
  {
    "type": "staticButton",
    "title": "G⇲",
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"Google Chrome\"\n\texecute javascript \"javascript:document.querySelector('video').requestPictureInPicture();\"\nend tell"
    },
    "align": "left",
    "width": 40
  },
```

**Comment by mehdi-S** [comment]
it seems not working the same way for google Chrome as the script doesn't start PiP

**Comment by Toxblh** [comment]
After tests, it's not possible now.
Should be work this solution, but chrome say to about, a user should self to do, not from external sources, like AppleScript.

```js 
{
    "type": "staticButton",
    "title": "G⇲",
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"Google Chrome\"\n\texecute front window's active tab javascript \"javascript:(async()=>{const video=document.querySelector('video');if(video.hasAttribute('__pip__')){await document.exitPictureInPicture()}else{await video.requestPictureInPicture();video.setAttribute('__pip__',!0);video.addEventListener('leavepictureinpicture',event=>{video.removeAttribute('__pip__')},{once:!0})}})();\"\nend tell"
      // To turn it on, from the menu bar, go to View > Developer > Allow JavaScript from Apple Events. For more information: https://support.google.com/chrome/?p=applescript"
    },
    "align": "left",
    "width": 40
  },
```

But you can use the extension for it https://github.com/Jasius/PiPPY
