### ISSUE TITLE
Do not show the weather right in Mojave system

### ISSUE THREAD

**Issue by FengweiHu** [Toxblh/MTMR#113]
<img width="1085" alt="2018-09-25 14 16 22" src="https://user-images.githubusercontent.com/4504959/45996222-fa999d00-c0cd-11e8-86dd-eba0360fe294.png">

**Comment by ad** [comment]
Try to register here: https://home.openweathermap.org
Then grab API key from here: https://home.openweathermap.org/api_keys
Then put it to your config "api_key": "..." in weather section

**Comment by FengweiHu** [comment]
ok, but I have tried for many times to sign up there all failed, it always reminds me "reCAPTCHA verification failed, please try again."

**Comment by FengweiHu** [comment]
I use vpn, now I generated one apices, and put it to the weather section, but still can't get weather data. check my attached pic pls.
<img width="1099" alt="2018-09-29 16 56 46" src="https://user-images.githubusercontent.com/4504959/46243602-b75e6780-c408-11e8-9e6b-1d5da85ff117.png">

**Comment by FengweiHu** [comment]
well, after a moment now it works, thank you!
