### ISSUE TITLE
update and all applescript ko, an idea ? 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [Toxblh/MTMR#115]
hello, I just made the maj, late many versions, and switch under mojave meanwhile.

no more of my scripts work, an idea?

Everything is ok when I launch them from the editor. But from MTMR it does not work.

A strange behavior, for example this script, seems to open the terminal, but not to launch the command.

```
tell application "Terminal"
	activate
	my makeTab()
	do script "ping google.com" in front window
end tell

on makeTab()
	tell application "System Events" to keystroke "t" using {command down}
	delay 0.2
end makeTab
```

```
  {
    "type": "staticButton",
    "title": "🚀 ",
    "action": "appleScript",
    "actionAppleScript": {
      "filePath": ".../test.applescript",
    },
    "width": 34,
    "align": "right"
  },
```

in fact, it's like just the first line was executed

**Comment by Toxblh** [comment]
Yes, I know about the problem. Sometimes MacOS don't ask about allow for AS actions for an app. I hope to found a solution to resolve it. Thanks

**Comment by PierreBrisorgueil** [comment]
hum, ok ! 

nice fix :) update is ok for actionAppleScript for me.

but always ko when we use it like a source :   

```
"source": {
      "filePath": "test.applescript",
},
```

`return " test"`

**Comment by Toxblh** [comment]
UPD: AppleEvents works in 0.18.2
But, `System Events got an error: MTMR is not allowed to send keystrokes.` The error about your case, also it's don't work via `osascript ./test.scpt` didn't create a new tab

**Comment by Toxblh** [comment]
> hum, ok !
> 
> nice fix :) update is ok for actionAppleScript for me.
> 
> but always ko when we use it like a source :
> 
> ```
> "source": {
>       "filePath": "test.applescript",
> },
> ```
> `return " test"`

About it. If a script has an error in `.applescript` it's broke execution if it saves like `.scpt` via AppleScript Editor, after error will continue execution

**Comment by PierreBrisorgueil** [comment]
yeah this is other thing 
system preference > security privacy > privacy > accessibility > check mtmr and it will be ok

no I have another issue with my script which do a return  =>

`return " test" ` work

set smallSize to 12
set listName to "mylistname"

```
set smallSize to 12
set listName to "iManage"

tell application "Reminders"
  set activeReminders to name of (reminders of list listName whose completed is false and priority is 1)
  if activeReminders is {} then
    set activeReminders to name of (reminders of list listName whose completed is false)
    if activeReminders is {} then
      return ""
    else
      set result to my theReduce(first item of activeReminders, smallSize)
      return result
    end if
  else
    set result to my theReduce(first item of activeReminders, smallSize)
    return result
  end if
end tell

on theReduce(theString, theNumber)
  if length of (theString) is less than theNumber then
    set result to " " & theString
  else
    set result to text 1 thru theNumber of theString
    set result to (" " & result & ".")
  end if
  return result
end theReduce

```

maybe again my encode with Script Editor, I check

**Comment by Toxblh** [comment]
what the problem? How did it look? Or the problem in first space?

**Comment by Toxblh** [comment]
ok I see.

**Comment by PierreBrisorgueil** [comment]
ok I think mtmr lost access to some things, reset is the solution. 

For example with reminders : 

system preference > security privacy > privacy > reminders > Uncheck and check again and mtmr could access to reminders again

**Comment by Toxblh** [comment]
in 0.18.3 will be

**Comment by Toxblh** [comment]
@PierreBrisorgueil pls check updates for MTMR, and could you write about results

**Comment by Toxblh** [comment]
"If I uncheck, relaunch mtmr, nothing is asked, everything show error." - It's correct, new privacy politic in mac os

**Comment by PierreBrisorgueil** [comment]
okok perfect :) thx for reactivity
