### ISSUE TITLE
can't re-open mtmr after closing

### ISSUE THREAD

**Issue by Arketsu** [Toxblh/MTMR#117]
OS Mac OS Mojave : version 10.14.1 18B57c
Hide Control Strip: ✅ Checked 

every time I tap the X to close the MTMR to use the auto corrector in the Touch Bar when I tap the icon on the control strip to open back the MTMR it does not open and I need to open the app again to make is work or click hide control strip 2 times.

**Comment by Toxblh** [comment]
confirmed
