### ISSUE TITLE
Debug output?

### ISSUE THREAD

**Issue by jacobsmith-fusionalliance** [Toxblh/MTMR#121]
Hello,

thanks for all the work on mtmr!

I'm trying to run a shell script on button press, but it's not firing - is there any additional debug output I can follow?

For context, here's what I'm trying to do:

```bash
echo 'called' > /Users/jsmith/Code/pealScrape/output

osascript -e "tell application \"QuickTime Player\"" -e "set quicktime to a reference to document 1" -e "tell quicktime" -e "open URL \"$1\"" -e "repeat until (current time of quicktime = duration of quicktime)" -e "end repeat" -e "end tell" -e "quit" -e "end tell"
```

```json
  {
    "type":"staticButton",
    "action":"shellScript",
    "title": "thanks",
    "executablePath":"/Users/jsmith/Code/pealScrape/playSound.sh",
    "shellArguments":["https://sound.peal.io/ps/audios/000/019/446/original/uploads_2F1536082270358-a2mzwz2j6ar-463d60035c9947868ea2e0694d8159f4_2FI_just_wanted_to_say_thanks.wav?1536082337"]
  },
```

I'm able to call the file directly with arguments (i.e. copy and paste of the form `${executablePath} ${shellArguments}`) and it works fine, so just trying to debug why the script isn't running (I added the "echo 'called'" line for it to  touch a file when it is called - even that is not there).

Thanks for any extra leads you can provide!

**Comment by Toxblh** [comment]
For debugging you can use Console.app with filter by process "MTMR"
![image](https://user-images.githubusercontent.com/2198153/47516202-c821c200-d87c-11e8-81d2-45948dbfd69d.png)
But your problem have here - https://github.com/matryer/bitbar/issues/196
and solution it's 
> This will also happen if you're missing an interpreter at the head of the file (I.E. #!/bin/bash or #!/usr/bin/ruby)

In your case `#!/bin/bash` need to add as the first line in .sh script

**Comment by jacobsmith-fusionalliance** [comment]
Awesome, thank you so much!
