### ISSUE TITLE
Issue Preferences

### ISSUE THREAD

**Issue by RoiTawa2000** [Toxblh/MTMR#124]
Hey there

Your Plugin is great! But I am not able to modify the Touch Bar, because every time I press "preferences" in the status bar, Adobe After Effects is opened. 

I can't really change the preferences and I don't know where to change them manually :/

But again, great work! :D

RoiTawa2000

**Comment by Toxblh** [comment]
Hey :) It’s standard behaviour. Then you click on preferences in status menu, it is mean open in standatd text editor in system file with config. In your system After Effects it’s standard text editor for JSON. 
Soon, I hope, I do UI for it in the app

**Comment by RoiTawa2000** [comment]
Oh thank you :D
