### ISSUE TITLE
0.19 is missed on release page 

### ISSUE THREAD

**Issue by idoo** [Toxblh/MTMR#128]
Currently, in docs, we can see that MTMR should be installed by brew, but on the releases page, 0.19 is missed. What is the current URL for download updates? Probably we have to update brew cask URL as well

**Comment by Toxblh** [comment]
It's ok. It's my plan, you will receive a new version via autoupdate

**Comment by idoo** [comment]
So, app will be distribute by private server now?

**Comment by vitorgalvao** [comment]
@Toxblh I see you have instructions to install via `brew cask` on the README. If you’re not going to be making later versions publicly available, we’ll have to remove the cask from the main repos and those instructions will break (unless you decide to host your own tap and direct people there).
