### ISSUE TITLE
Feature request: show/hide dashboard build-in command

### ISSUE THREAD

**Issue by vithar** [Toxblh/MTMR#143]
I want to show os x dashboard on button keypress.

Can can to this using such button:

```
  {
    "type": "staticButton",
    "title": "🎱",
    "action": "shellScript",
    "executablePath": "/Applications/Dashboard.app/Contents/MacOS/Dashboard",
    "width": 70
  },
```

But I can't hide it by pressing the same button again.

Can you add native command to show/hide dashboard?

P.S. Thank you for such great tool! :)

**Comment by ptunay** [comment]
Here's a workaround I use: 

       {
        "type": "staticButton",
        "align": "right",
        "title": "ᜇᜊᜓ",
        "bordered": false,
        "action": "keyPress",
        "keycode": 103
      },

where the keycode is [mapped to F11](http://macbiblioblog.blogspot.com/2014/12/key-codes-for-function-and-special-keys.html) which I set to open Dashboard in Mission Control. 
Hope this helps, cheers! 🍻
