### ISSUE TITLE
Feature request: network speed meter

### ISSUE THREAD

**Issue by dennysortega** [Toxblh/MTMR#147]
Just like the Battery in the Touch Bar it would be awesome for MTMR to show the network speed meter on the Touch Bar. Like: an up arrow showing the speed of the uploading and an arrow going down to show the downloading speeds. 

Edit: to make it a bit clearer, just like iStatMenus does it. Posting a screenshot as an example. 

<img width="75" alt="captura de pantalla 2019-02-21 a la s 08 34 55" src="https://user-images.githubusercontent.com/47858462/53176383-94993f00-35b3-11e9-9d91-1c7457365d04.png">

**Comment by Toxblh** [comment]
v0.20
