### ISSUE TITLE
What is wrong with my preset? It was working when I made some changes and then quit my text editor. 

### ISSUE THREAD

**Issue by Frityet** [Toxblh/MTMR#150]
[items.json.zip](https://github.com/Toxblh/MTMR/files/2908086/items.json.zip)
(GitHub doesn't allow .json)

**Comment by Toxblh** [comment]
{ "type": "escape", "width": 64 },
{ "align": "left" },

should be 
{ "type": "escape", "width": 64, "align": "left" },

**Comment by Toxblh** [comment]
in start of json

**Comment by Toxblh** [comment]
nice preset 👍

**Comment by Frityet** [comment]
Thanks!
