### ISSUE TITLE
The wrong `⎋esc` button 

### ISSUE THREAD

**Issue by Loovemaker** [Toxblh/MTMR#154]
The `⎋esc` button doesn't exactly same as that in the native Control Strip, it seems to that the buttons are 'locked' when pressing some keys:

-   I cannot exit from Switch bars (`⌘` `⇥tab`) without triggering anything (when holding `⌘` ) by pressing `esc`.
-   `Force Quit...` ( `⌘⌥` `⎋esc` ) cannot be triggered.

Furthermore:

-   (very low possibility and can be denied) Finder Browsers in some specific apps cannot be closed by pressing `⎋esc`.

**Comment by Loovemaker** [comment]
Environment: macOS 10.14.3

**Comment by Toxblh** [comment]
thanks - I'll see how to fix it

**Comment by Loovemaker** [comment]
Report update:

I've roughly tested out that maybe **all other** functions around `⎋esc` works:

-   "Force quitting the current app" ( `⌘⌥⇧` + `⎋esc` ) works quite surprisingly.
-   [ `⌘` ,  `⌥`  or `⇧` ] + `⎋esc` also works. (I heard an 'beep' alert due to no bound keyboard shortcuts)

<3  hope an easy fix

**Comment by nannery** [comment]
Another example that I've found of `⎋esc` not functioning is when command tabbing—when holding down command during tabbing, MTMR's `⎋esc` does not exit the interface as it does when using the stock `⎋esc`

macOS v10.14.3
MTMR v0.20

**Comment by straccio** [comment]
I have a problem after this..
I have mapped AlfredApp to alt+esc hotkey and i think that the escape button no longer see the alt pressed, always trigger esc.

**Comment by gaastonsr** [comment]
I still experience this and I'm on the last version 0.20.3. Should it be fixed @Toxblh ?

**Comment by straccio** [comment]
I'm on 0.20.3 and i have the issue https://github.com/Toxblh/MTMR/issues/154#issuecomment-490659491

**Comment by FinHorsley** [comment]
Seeing the same problem when trying the following
- trying to exit spotlight search, `cmd + space`
- `option + esc` to open force quit
##
#### Environment
- MTMR Version: 0.20.3
- MacOS version: 10.14.4 (18E226)

**Comment by Toxblh** [comment]
@FinHorsley 
In these situations - TouchBar apps fully blocked - you can quit/hide MTMR and try to do something apps as Finder or Google Chrome. You can't fire any action, MTMR is app and also can't handle action if you in cmd+tab or cmd+space.

**Comment by straccio** [comment]
In my case is not blocked, the app is working but didn't get modifier keys on escape button.

**Comment by Toxblh** [comment]
@straccio in your case best use 20.1 I'll think how to present the new ESC button. Because I didn't find a universal solution for that. In one case good work for Alfred and other applications, in opposite good works for system hotKeys

**Comment by straccio** [comment]
On 20.3 this trigger correctly Alfred (alt-esc) but not cmd+alt+"nEsc"
```
{
		"type":"staticButton",
		"action": "keyPress",
		"keycode": 53,
		"align": "left",
		"title":"nESC",
		"width": 74
}
```
Otherwise the escape type trigger cmd+alt+esc but not alt+esc (alfred)

**Comment by Toxblh** [comment]
@straccio  I told about it. In use code - then for ESC in 20.3 I use https://github.com/Toxblh/MTMR/blob/master/MTMR/KeyPress.swift#L36 .cgAnnotatedSessionEventTap and this perfect work for system hotKeys as ⌘⌥⇧ + ⎋Esc, but doesn't work for some applications, and in your nEsc - used https://github.com/Toxblh/MTMR/blob/master/MTMR/KeyPress.swift#L26 .cghidEventTap that previous implementation - this correct work in Alfred but doesn't in system

**Comment by FinHorsley** [comment]
> @FinHorsley
> In these situations - TouchBar apps fully blocked - you can quit/hide MTMR and try to do something apps as Finder or Google Chrome. You can't fire any action, MTMR is app and also can't handle action if you in cmd+tab or cmd+space.

@Toxblh so to enable `esc` I have to grant access so that MtMr is not blocked?

**Comment by Toxblh** [comment]
@FinHorsley You can't change the behaviour in MacOS - I think for reducing misclicks then you do cmd+tab or cmd+space(change language).

**Comment by gaastonsr** [comment]
> @FinHorsley
> In these situations - TouchBar apps fully blocked - you can quit/hide MTMR and try to do something apps as Finder or Google Chrome. You can't fire any action, MTMR is app and also can't handle action if you in cmd+tab or cmd+space.

Using escape to exit spotlight or while I'm switching apps is a common for me. You think it should be fixable @Toxblh?

**Comment by Toxblh** [comment]
Okay, I really tried to find any solution about how to better simulate Esc, and I don’t know how to deep hack touch bar app from Apple to understand how to do the same. Because solution in 0.20.2-0.20.3 is not good, yes you can open Force Quit Apps, but very more affected other apps, as Alfred, Spotlight and some text editors. I will revert the changes to version 0.20.1.

If you find how real simulate in mac os Esc button - I’m open for PRs from you. Any implementations via CGEvents - doesn't work fully. An easy test for understanding works or not:
1. Try to open Force Quit Apps via cmd+option+esc
2. Try to close Spotlight input
If one of doesn’t work - is fail
