### ISSUE TITLE
Haptic feedback on press rather than release

### ISSUE THREAD

**Issue by guatedude2** [Toxblh/MTMR#173]
It would be nice to have feedback on press rather than release. It's more intuitive to feel the button pressed rather than released since its very probable you wont feel it since your finger would be moving away from the key.

**Comment by bobrosoft** [comment]
@guatedude2  I fixed that in my fork, will push it to that repository later

**Comment by guatedude2** [comment]
Amazing @bobrosoft ! Thank you!

**Comment by bobrosoft** [comment]
@guatedude2 should be there now 🍷

**Comment by guatedude2** [comment]
confirmed! Thanks @bobrosoft!
