### ISSUE TITLE
Mojave issues: custom apple script button not working, weather is not loading

### ISSUE THREAD

**Issue by vladimirdolzhenko** [Toxblh/MTMR#176]
### Weather item is permanently loading 
I use a weather type 
```
{ "type": "weather", "icon_type": "images", "units": "metric", "align": "right" }
```

MTMR has all (reasonable) permissions (Security & Privacy > Privacy > Location services > MTMR.app is on) but weather button shows only hourglasses icon. Restart of app doesn't help.

**Comment by pinko** [comment]
You need to add an api_key, which you get by signing up for a free account with https://openweathermap.org.

**Comment by vladimirdolzhenko** [comment]
Thanks @pinko - indeed, it works now

@Toxblh I guess it is worth to update doc

**Comment by Toxblh** [comment]
But.. https://github.com/Toxblh/MTMR#weather

**Comment by Toxblh** [comment]
Okay a bit improve about api_key is required :)
