### ISSUE TITLE
mirophone mute button

### ISSUE THREAD

**Issue by sdubrul** [Toxblh/MTMR#177]
Feature idea: a button to mute/unmute the mic.
Would be very helpful during conference calls taken from the noisy house :)

**Comment by mjabdulm** [comment]
Hi,

You can use this in the preferences until we have an inbuilt plugin.

 {
    "type": "appleScriptTitledButton",
    "align": "right",
    "refreshInterval": 2,
   "source": {
      "inline": "if input volume of (get volume settings) = 0 then\rreturn \"Muted\"\relse\rreturn \"Unmuted\"\rend if"
    },
   "action": "appleScript",
    "actionAppleScript": {
      "inline": "if input volume of (get volume settings) = 0 then\rset level to 100\rset volume input volume level\rreturn \"Unmuted\"\relse\rset level to 0\rset volume input volume level\rreturn \"Muted\"\rend if"
    },
},

I'm trying to find if we can display an emoji in the place of the text: Mute and Unmute

**Comment by mjabdulm** [comment]
Here is the closest, I could get:

{
    "type": "appleScriptTitledButton",
    "align": "right",
    "refreshInterval": 2,
   "source": {
      "inline": "if input volume of (get volume settings) = 0 then\rreturn \"🔇\"\relse\rreturn \"🎙\"\rend if"
    },
   "action": "appleScript",
    "actionAppleScript": {
      "inline": "if input volume of (get volume settings) = 0 then\rset level to 100\rset volume input volume level\rreturn \"🎙\"\relse\rset level to 0\rset volume input volume level\rreturn \"🔇\"\rend if"
    },
},

You can even replace the "speaker" mute button using this method

**Comment by sdubrul** [comment]
Yep. Works as charm. Thanks @mjabdulm

**Comment by gtataranni** [comment]
no need for returns if your title already checks for the current volume
```
{
    "type": "appleScriptTitledButton",
    "align": "right",
    "refreshInterval": 2,
    "source": {
      "inline": "if input volume of (get volume settings) = 0 then\rreturn \" 🤫 \"\relse\rreturn \" 🎙️ \"\rend if"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "if input volume of (get volume settings) = 0 then\rset level to 100\rset volume input volume level\relse\rset level to 0\rset volume input volume level\rend if"
    }
  },
```
