### ISSUE TITLE
Spotify app doesn't show track when connected via Spotify Connect

### ISSUE THREAD

**Issue by fakeharxy** [Toxblh/MTMR#182]
Love MTMR, everything works great, but when streaming to a speaker using Spotify Connect, MTMR just shows  '-' where the track normally is... any idea why?

**Comment by Toxblh** [comment]
hmmm! That's happen after update in Spotify. okay I'll try to see that

**Comment by fakeharxy** [comment]
Hey Toxblh is there any solution to this? I see that BetterTouchTool does the same thing when you connect on Spotify Connect, so maybe it's just not possible to get around?

thanks,

**Comment by MikeOne** [comment]
Old issue is seems - but I'm seeing the same. I wondered of there is a solution for this.

**Comment by fakeharxy** [comment]
I would still love a solution :)

**Comment by leventbk** [comment]
Hey! 
I have same problem. All permissions is ok and sometimes it shows the song names but after a next track doesn't  :/
but MTMR is the best !!!!

**Comment by MikeOne** [comment]
It seems this is a spotify issue. The external interface Spotify provides is pretty horrible and limited unfortunately..

**Comment by unbreakableglass** [comment]
It started working for me on yesterday after the latest Spotify update.  It was definitely a Spotify issue as the name of the track was not appearing in the Now Playing section in the notification centre.

**Comment by MikeOne** [comment]
HA! That's funny. Just realized I'm looking at the track name - while being connected to a remote speaker. They must have changed something indeed. Cool!

**Comment by MikeOne** [comment]
Now if Spotify would only allow volume control through AppleScript - I'd be completely happy ;-)
