### ISSUE TITLE
Possibility to disable Haptic feedback

### ISSUE THREAD

**Issue by xhaythemx** [Toxblh/MTMR#185]

**Comment by mjabdulm** [comment]
Also, can you please provide an option to enable a sound feedback?

**Comment by inferusvv** [comment]
Voting for this feature. Really annoying when you press on touch bar, but feel feedback under trackpad

**Comment by shtreifling** [comment]
Can someone help me to disable the haptic feedback for some buttons?

what i try
{
"type": "staticButton",
"width": 72,
"align": "left",
"title": "F1",
"action": "keyPress",
"keycode": 122,
"HapticFeedback": "false"
},

is there a way for disable haptic feedback for custom types?

       {
           "type": "close",
           "width": 45,
           "align": "left",
           "HapticFeedback": "false"
       },
