### ISSUE TITLE
Weather icon at night

### ISSUE THREAD

**Issue by matteo95g** [Toxblh/MTMR#201]
At night, the weather icon shows a sun 🌞 when it should show a moon, maybe ?

**Comment by matteo95g** [comment]
It would be great that the icon image can be customizable !

**Comment by bobrosoft** [comment]
Unfortunately there's no night variations for "sun in the cloud" emoji, only moon without clouds is there, so day/night icons not implemented as there's only one icon available. And didn't want to use custom images there yet, only emojis atm.

**Comment by matteo95g** [comment]
Well, maybe it would be better to show a moon at night instead of a sun, what do you think ?

**Comment by bobrosoft** [comment]
@matteo95g if only that... but if "clear" weather will change to "low clouds" then 🌖will change to 🌤 at night — would look strange, no? %) So, possibly better to leave "as is" then.
