### ISSUE TITLE
get data from json

### ISSUE THREAD

**Issue by alonewolfx2** [Toxblh/MTMR#213]
i am getting data from http request but i cant show it in button.
how can i get data and show in button name with applescript

**Comment by bobrosoft** [comment]
I'm using NodeJS script to send requests and process JSON responses, but that may look heavy. Still there some ways to do it with AppleScript, google for it. Also you can use shell script and utils as [jq](https://stedolan.github.io/jq/tutorial/) (not a standard one).

**Comment by alonewolfx2** [comment]
i am using for another touch tool with this applescript and working very well. bu same code not getting any data. actually seems getting data but not showing
````
tell application "JSON Helper"
	set json to fetch JSON from "http://static.xxxxx.com:8080/xxxxx/get/V0"
	set countryName to "Son: " & json & "°C"
end tell
````

**Comment by bobrosoft** [comment]
I don't see that your script return anything, so nothing displayed ... there should be `return temprature` there, no? When you run it in AppleScript editor, it should display it in "Result" section if working properly.

**Comment by alonewolfx2** [comment]
actually working and getting data. but not showingon mtmr
<img width="715" alt="Adsız" src="https://user-images.githubusercontent.com/9630594/65166012-8d061f80-da48-11e9-8cf7-c4759991b64d.png">

**Comment by alonewolfx2** [comment]
ok solved. it seems if i put it into file and include its working ""filePath": "/Users/Shared/MTMR/depo.scpt" working well.
