### ISSUE TITLE
Mute button

### ISSUE THREAD

**Issue by kd240** [Toxblh/MTMR#222]
Hi there again!

Maybe add 2 icons for mute button, so when it is muted is shows the crossed volume icon, and when it is not muted, show the regular volume icon

KR,
Kristian

**Comment by mjabdulm** [comment]
Please refer #177

**Comment by mjabdulm** [comment]
#177 is for mic mute and the below code is for speaker mute:

  {
    "type": "appleScriptTitledButton",
    "refreshInterval": 2,
    "align": "right",
   "width": 35, 
    "source": {
      "inline": "set curVolume to get volume settings\rif output muted of curVolume is false then\rreturn \"🔈\"\relse\rreturn \"🔇\"\rend if"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "set curVolume to get volume settings\rif output muted of curVolume is false then\rset volume with output muted\relse\rset volume without output muted\rend if"
    },
  },

**Comment by kd240** [comment]
Thanks, closing

**Comment by gtataranni** [comment]
no need for returns if your title already checks for the current volume
```
{
    "type": "appleScriptTitledButton",
    "align": "right",
    "refreshInterval": 2,
    "source": {
      "inline": "if input volume of (get volume settings) = 0 then\rreturn \" 🤫 \"\relse\rreturn \" 🎙️ \"\rend if"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "if input volume of (get volume settings) = 0 then\rset level to 100\rset volume input volume level\relse\rset level to 0\rset volume input volume level\rend if"
    }
  },
 ```
