### ISSUE TITLE
Custom apple script button not working

### ISSUE THREAD

**Issue by AlaricCalmette** [Toxblh/MTMR#23]
Awesome work guys! That's a great tool!
However I'd like to have a mute button instead of having to slide down to zero.

I tried multiple ways to add a custom applescript button but none worked 😔

This is my last attempt : 
```
{
    "type": "staticButton",
    "align": "right",
    "image": { "base64" :"a real base 64 that is way too long"},
    "action": "appleScript",
    "actionAppleScript": {
        "source": "/Users/acalmette/mute.scpt"
    },
    "width": 36
  }
```

I tried to inline the script which is : 
```
set curVolume to get volume settings
if output muted of curVolume is false then
	set volume with output muted
else
	set volume without output muted
end if
```

And it didn't work neither.

Note that the script works when played by script editor.
Any ideas?

**Comment by Toxblh** [comment]
```{
    "type": "staticButton",
    "title": "mute",
    "action": "hidKey",
    "keycode": 7,
    "align": "left"
  },```

**Comment by Toxblh** [comment]
Agree, not clear :) 
I'll add soon inner it

**Comment by vladimirdolzhenko** [comment]
Well @Toxblh it is still not clear what have to do in case of custom apple script button not working.

```
{
    "type": "appleScriptTitledButton",
    "align": "left",
    "source": {
      "inline":
        "if application \"iTerm2\" is frontmost then tell application \"iTerm2\"\rtell current session of current window\rreturn (variable named \"user.dirInfo\")\rend tell\rend tell\rend if\rreturn \"\"\r"
    },
    "refreshInterval": 1
  }
```
(script fetches user variable (like path, git branch etc) set by iTerm2)

Script works fine with `osascript /path_to_script/script.scpt` but MTMR reports permanently `error` - even if I change button to 
```
{
    "type": "appleScriptTitledButton",
    "align": "left",
    "source": {
      "filePath": "/path_to_script/script.scpt"
    },
    "refreshInterval": 1
  }
```

It still does not work. Could you pls help with it ?
