### ISSUE TITLE
New app icon suggestion

### ISSUE THREAD

**Issue by jonasdebeukelaer** [Toxblh/MTMR#248]
Hey, mucked about with logo ideas for this a little while back, figured I might as well share if you like it and want to use it/develop the idea.
<img width="818" alt="MTMR_idea_v4" src="https://user-images.githubusercontent.com/9272376/70363769-a4072180-1881-11ea-92f7-03a2d269adba.png">

**Comment by ofekashery** [comment]
@Toxblh What do you think about this logo?
![MTMR](https://user-images.githubusercontent.com/16443111/99146858-9d358100-2684-11eb-9f6c-fcfc7d3547bd.png)

**Comment by Toxblh** [comment]
If you would like - I open for any ideas and PRs.
@jonasdebeukelaer in general very nice idea with "pro hacker" app.
@ofekashery looks so good, better than my try
