### ISSUE TITLE
Pomodoro widget does not have an initial icon

### ISSUE THREAD

**Issue by s3k** [Toxblh/MTMR#249]
Found a strange bug: the tomato icon is not displayed after MTMR launched.
Just empty button without any labels.  But by pressing this empty button the widget works properly.

Branch: master
Last commit: e9e5a6f739ae1c1fc52a7fd353fccf7817e9783e
Version: 25
OS: Catalina 10.15.1

How to fix it quickly: just add spaces around tomato emoji.
It's a dirty hack, but it worked for me.

```
// PomodoroBarItem.swift
...
private let defaultTitle = " 🍅 "
...
```

**Comment by maandagdev** [comment]
@Toxblh this can be closed I think?

**Comment by Toxblh** [comment]
@maandagdev  yes
