### ISSUE TITLE
Feature Request: timeout for group

### ISSUE THREAD

**Issue by boesing** [Toxblh/MTMR#250]
Hey there,

I would love to have a little feature request. What about a new parameter for groups which defines a timeout until the group will close after opening.

Something like:

```
{
 {
	  "type": "group",
	  "align": "right",
	  "bordered": true,
	  "title": "foo",
          "closeAfter": 10,
	  "items": [
          ]
}
}
```

`closeAfter` could be something like seconds and after X seconds inactivity, the group will close.

Could definitely use that feature :-) 

Thanks in advance,
Max

**Comment by maandagdev** [comment]
Hi Max,

I am currently trying to implement this, have you looked into the code before making this issues? 

Not sure what the best way would be to implement this since I can start a timer whenever the group popover is created but I cannot log any touch actions within the touchbar for some reason.

**Comment by boesing** [comment]
No I didnt because I am not familiar with swift. Just wanted to bump that feature 😅 
So there is no event or something when clicking on an element inside the touchbar?

**Comment by maandagdev** [comment]
I am new to swift as well, but I thought maybe if you looked into it, it might be easier for me to implement it haha. I will have a go at it, there probably is some sort of event I can hook on but I just need to figure out which one.
