### ISSUE TITLE
The ESC sometimes does not take affect

### ISSUE THREAD

**Issue by gaohuia** [Toxblh/MTMR#251]
As a heavy vim user, i use ESC a lot.  But when the ESC was pressed sometimes,  it did not take affect. It happens a lot, and can easily reproduce.

To make sure i did have pressed the ESC, I recorded a video.  It proofs my words, the last ESC did not take affect.

[https://github.com/gaohuia/test_event/raw/master/1576136644484506.mp4](https://github.com/gaohuia/test_event/raw/master/1576136644484506.mp4)

**Comment by Toxblh** [comment]
check you 🍏→ System Preferences → Security and Privacy → tab Privacy → Accessibility → MTMR settings, or re-tick it

**Comment by gaohuia** [comment]
I don't think it works to do so. As you can see in the video, the ESC works most of the time. 
Will try it tomorrow.

**Comment by Toxblh** [comment]
hmmm...
HMMM....
I think, I know that is that - #154 #165 
Yes, if you would like to use ESC on touch bar you can del esc widget and use MTMR without "Hide Control Strip" option, or do the same as I, remap CapsLook to esc in 
![image](https://user-images.githubusercontent.com/2198153/71990901-1fb31000-322c-11ea-8456-4280929b6420.png)
