### ISSUE TITLE
Gesture with single finger slide?

### ISSUE THREAD

**Issue by dataplayer12** [Toxblh/MTMR#252]
I don't have enough space in the middle to fit three fingers to change the brightness. It's a hit and miss thing. Would it be possible to implement a single finger slide gesture? It doesn't have to be the default setting, but for the ones out here with thick fingers or busy configs, having the option to change brightness with one finger would be amazing.

**Comment by bobrosoft** [comment]
When last time I touched "gestures recognition" code, it was so hard to make all gestures and scenarios to work normally — almost pissed me off, some black magic %) Don't think that will be implemented. Also, single finger slide reserved there by native functionality which allow user to scroll long titles if they occur there in the bar, can be seen in "music" plugin for example if song has a long title.

**Comment by dataplayer12** [comment]
Got it. Thanks for clarifying that.
