### ISSUE TITLE
Enhancement: button to toggle MTMR

### ISSUE THREAD

**Issue by jkhdesign** [Toxblh/MTMR#259]
Hiya! Not sure if this is possible, but I would love to see a button that toggles MTMR on and off (though the button would have to remain present somehow when the app is toggled off) to allow the native touchbar to be used — almost always I prefer to use MTMR but occasionally I wish I could briefly use the functionality an app utilizes the touchbar for (such as the emoji picker in Messages or the color picker in the Adobe suite).

**Comment by Toxblh** [comment]
I think `exitTouchbar` can help to you

**Comment by jkhdesign** [comment]
Perfect, thanks!!
