### ISSUE TITLE
Add "show launchpad" and "show desktop" buttons

### ISSUE THREAD

**Issue by Sn0wCooder** [Toxblh/MTMR#263]

**Comment by geneho** [comment]
Do you have the solution to this?

**Comment by Sn0wCooder** [comment]
> Do you have the solution to this?

Yep, just screen the original icons and use them as icons for a command.
Do you want the code?

**Comment by geneho** [comment]
Yes please.

**Comment by Sn0wCooder** [comment]
> Yes please.

You can see my preset here https://github.com/Toxblh/MTMR-presets/tree/master/sn0wcooder
