### ISSUE TITLE
Apple Music widget not working

### ISSUE THREAD

**Issue by dyraosx** [Toxblh/MTMR#270]
Hi,

This has been discussed before (https://github.com/Toxblh/MTMR/issues/211)

In 10.15.3 - I can't get apple music working, where Spotify does. I've changed the code to read \"Music\" to no avail.

Please advise

Thanks

**Comment by zwb124** [comment]
try it

{
    "type": "appleScriptTitledButton",
    "source": {
      "inline": "if application \"Music\" is running then\rtell application \"Music\"\rif player state is playing then\rreturn (get artist of current track) & \" – \" & (get name of current track)\relse\rreturn \" \"\rend if\rend tell\rend if\rreturn \"\"\r"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "if application \"Music\" is running then\rtell application \"Music\"\rif player state is playing then\rpause\relse\rplay\rend if\rend tell\rend if\r"
    },
    "longAction": "appleScript",
    "longActionAppleScript": {
      "inline": "if application \"Music\" is running then\rtell application \"Music\"\rif player state is playing then\rnext track\rend if\rend tell\rend if\r"
    },
    "refreshInterval": 2,
    "image": {
      "base64": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAJplWElmTU0AKgAAAAgABgESAAMAAAABAAEAAAEaAAUAAAABAAAAVgEbAAUAAAABAAAAXgEoAAMAAAABAAIAAAExAAIAAAAVAAAAZodpAAQAAAABAAAAfAAAAAAAAACQAAAAAQAAAJAAAAABUGl4ZWxtYXRvciBQcm8gMS41LjUAAAACoAIABAAAAAEAAABAoAMABAAAAAEAAABAAAAAAL16SVUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAAOXaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA1LjQuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIj4KICAgICAgICAgPHRpZmY6UmVzb2x1dGlvblVuaXQ+MjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPHRpZmY6WFJlc29sdXRpb24+MTQ0MDAwMC8xMDAwMDwvdGlmZjpYUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgICAgPHRpZmY6WVJlc29sdXRpb24+MTQ0MDAwMC8xMDAwMDwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjY0PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6Q29sb3JTcGFjZT4xPC9leGlmOkNvbG9yU3BhY2U+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbWVuc2lvbj42NDwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+UGl4ZWxtYXRvciBQcm8gMS41LjU8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgICAgPHhtcDpNZXRhZGF0YURhdGU+MjAyMC0wMy0xMVQwNzozNTowOVo8L3htcDpNZXRhZGF0YURhdGU+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgpBvXdBAAAUfklEQVR4AeVbe5AcxXnv2fft7b0l3emJTkZCryAXxdtCRQojjCplOyYRIcGUCUR2WcZ5OBUcsIkIWMRxhchUysTERBFxSASuAimIoLKFTNkB64UCAklFGaTjJJ3u/dy93dmd2fx+3dOzs3Oze3sg5Z/0qbdf37u/7v6mZyTE//Nk/B/pb5w7d66tqanpqnA4vMIWolMUi7OR60UoJFCmhWH0Q5ZTecs6YVjWocbGxkG0ixdbvotigGKxaExMTCw3wuHPQL21UO5K5IVQtFZ+VLwbOIeFbf/Csqy9DQ0NJy6GMWoVqCbe4+Pjc2zbWB+Jhu4zDOPqmpBqAIJBCXWokLceTxvFn81rbByoAa0mkAtigK6urpbm1tbNkXD4W+Aar8YZhqk2DCeZ1uuLVqHw4ODg4JOdnZ0jVYnVMFhdmukJGMOjo1+PRiJbAZoMAg9hjWMcSx2LAcpPx1Cqjx/btkS+UECJHSM4pQuWtaW5sfHvMDyt1YJJQKRKA9P1DwwMXB1PJP4JJC73w0qlo0rp6Wbcj+sXiB5hwQj5fKAxMGwfz6TTd3R0dBzz06qljWmZWXruuefCQyMjD0RjiVch2+UUUGcqHo/HRAI5jLpUhnMzg8wV4M2co3AoDJpx0I5LT9L8UIKFsao+1XB4ZGTsm5RtZtrM0AOOHj3a3LlkyQ+EEbrDO1NUPBaD0uEZ21PKq2nRTrruV6Q0ZgicCiKXN4VtlS8PeMPO/r6+TUuXLh3z41dqV+I3Bf7EiRNtHXPn78MyXuMOAjsWjSLH3K6PXalZIiFMMy9MGMK7A8B7jvWeP/ep5cuXj9ciS03s9u7dW3/l1dccDRnGUpcoMJN1dWpzczs/akWLoefZX06lqzFsaJzJZPynx0DveXPJ8uWzpzXCtD67adOm6FVXX/MaGC7Va48bW7IuiU09VLZevWvXX6++D0BhiQBF/aUPEawJ5P6xnUyqidDyoZw1e070wLvvvts61XTlPdqQ5b1Oa8uWLZGv3ffHL2Nh3qwBEMpC+QSUL6Hq+dIwwSXhgyCD+rAXkD7+mYMjIvvrblE41SPsc0OimDFF4203ithlC8vZwHCZbFYUcHTqZFvWS4cPHfydDRs25HSfvyxp4Rvhjrp23Y1bcIZ/S+9MVL4+GXjc+7Bn1qSytlUQFpS1e/qE1TMgTCidP9klwqOTIhyrE8VIVNgijIy44pqVoume9cpbPKzoAZnMpEB84PbCIN+d2z7nL9FBS09JFQ3wwQcfrks11r+mMbjTU3nvzOuxKaVDlYXiqjqcbmHn88KYnBT2eFrk33tfZF9/U4Tf6xIxTF4omRIFQylqGxFhY5lJxbncYAALOX7VZaL5Hjgll4sv0QjjExMYcseKmYnJTy9evOBVH6hsRoI69+/f35xM1e0p2g4RSF6HDQ/aB5vRQ0Qq6aBpEYywIfLDIyL3+kFR3PuqSPQO4Fyvx6zGMJ+GiAooGk0KOxaWyltsU3GZaQxkGKUIaN3PXWCKAcgcOZVKifGxcW0EI1EX346RTuTycxMdQQYwLl22/EEYMCWZAEju9lyTJauiNzhppfXo5N59ov7F/xKJnIlYGbMYhnLJRqmQnlnOqlbS4uzrLBV22m49JCIYD0wOc9ohgX0qnc5osEXdZ87vWLig4y50lIk45RQ4duzYb2Ctb6YLMeMBR8by1D0wk6J3zOFALkUYrW7/ARHNY2JCcWGHY1CUsxuFK0eEBRe3UJftEPpCqq+AfpnRV0Bf3ilZZ7bpiWBaLfP5I4KsYcIRY+PBY8cWQKyy5DdAqLml7dtAqtOItKRUBr+BfxTE++cRjJxCRc4uNzCVtcJSaWkAKE3FZaYRkMNQnBl9VN5CKJyXfcoABbTBkv+q5jrILuGkTCLW0dz6BE62Mp3LGnv27JmDdf5bNtY+My1YOuuhJpn6cjUJCCtnnMo7M+0qToXRV+DsytKZdSwRPdNaaRPK59FvMuM0sOTGSHmCsxISxgdcLAbejj5GKPz5jRs3rvS6gHcPMFauXvN9EJVm426fxK5PJqVUVCciF5nT7Y6yz5+ASwNwm7PxK7O7uYWgCHZ1zCYVknW59lFHnzwJZBuxP8qihFGbYAHLEsSknmTpZ61kUr98gMrgxNEpXtdwJ+ruseh6wKpVq6JGyLhRW5Wzr7QkoVKW7k7Lu3/OKEBoK5U5M6rfgvJypo0YlIo5dc482sh08TxLx+1NnAzujMNLstg/rPo6EVuxQOSwEUoPCPE08snkylOSjDXoJJ8iS3qFNu/atSulDaI9wHhq+/Y1OPZmq1s7QyQSWPvkMW2qBEQL2NjsYhADGyA8ikeYhdJCTGEjF5CVF4Rw+YFJ5R3C7GaR/ESHiC2aJWKzGmSO1MelIsd/clCMvTsAg8EjtIWnlQ9XVOVekFq6fNUGoO0kqmuA9tntj8Bi8qCPRMLuc/e09P3+50Hg/Y/c9GAEur90dZYI1OwEbs6gbLi9ScTntorYUig9v1WEYti5eQvksStvhQyKBkPk8PSZ5xKgfWuZIcjHII6y2JgQplgk+hkUzyEXpQEQ9jYA4BYd+ESw2Xj4E6dyCgCkTWQ3BCxAecOICwtGNS6ZJcIr5ou6KxaLyNwWSbPoCVvZYRdKYawE8PwUcN+QhQFYakdXO4AWQs2Gyx+4hjPEE2FiIi2pFY3iOlS4/C1pgFnz5nXwsVKnKHbOmqzrIGiGir2jPMZ4YcM9oAgjRG/9pIivX6FZTFXUT8SFLFUKWEI0AE8DtaY5puRWvFW9pIkeVctgfBwhsiRnLNm3778X3HTTp7poBSNuROdz9qUHAIIPPWqNoQ+GUXWHFyn4srQd+li6mWBo5KF8HgeL3YATpQxVz6FTAlb+sayQC9jQspgckzdPkliJYSUctx+8mbSesztaf5NtaYBUY9N1DnsRons5dGETh5FSpkRMQ1cpHYXycH+TSwCsXPwKCgaNa2E4xrWfw+lkYjkpWMrliKhtQZG9dUcFFM4EKJlxz3gt+7gEjHAk9Em9/rlhKFAOe2uqXblTj2tfVuuPHmChK4F4n4JVSsqFp45KFAwaQOapkcGFqzwFpL848F66leoAZWyj9TRCoU+wiwbApIeX0aJMNEA1QSVQ1R/Q8WhDD8jz6EMwU8GckppX7inkOQgaeciWw/rPSQ8ANVdQD8MpyKUOxjZ53CMyITpsRiENYOB4mK+lllYi4So0OSRlIqUpCaNSMJa40UHwk2O0J5fAFOAZdGAJ0AOwB/BZQC8BRYDSIGnBnKpfhxD2EM9mj+d7ZQC6RZMfWGpIogHJYVcBxDNKAyAIyhkMiJyNNYCeKzgV8CWtE0vGESbuFuQmGMRdRXGSgpRCi+LSxBJwvKZoW/IqW+4BgOO54iJqIBevUiVAYAWqxXY8AIex9AAfHY3uOtwUgZWnEY1D0gMiiBqdZeqI7KEaQMA7iuGSbtzrnEgQhHBzUJSXffKY8CBVrXr4aWUUvDOAIoclkA1hA8PsaSNrmh70oPlUYJowZpc0cnwyxBJgUviaigZUaP5fjuLFiWsAGEJGXDIQwhoYwGPDIiLJl5FTTeunV2pjc6Ji8jlRcsGQKwvWLR51sxBcLoESVu01Rz+DXgQ6WWyCeZRyJjHGYcVOGyKYNEctvEnSqmETxBsV5QGIRu0PcSxIA/C1U3VSPgaaIrE0oqfM4knPhMtS+JL7KRpT7IVuogb3wwPgBSZOk4I0usOObKUFNKZPPk8zj8tYLQM2fsbFRS4EO5PNnOQAM19J63pwCSwJy7KUpeSUgZnJqZvwgEk++sqYSw3pXx9oGaqHhOynB/z0LN4Sw/1pABnOUA7+ufLo+tSSwpqOAQiPdwb8JEcGQsVsJnugri55LzuUlTALsCrg5HRIA3NQJq/Yuq+kdxkIGiae97O8/cEfGdeSyDuK3b5rMCeOnrPEqXRY9OSgeKJFKowpcpSu8r0BhXbkJ08ef1zewJQi5M3CW4TgHlA8d6b7eHOrejrjmxV+nKAiQo4qOhLL/Sk3idvtrwDXRKhhyusvCq0eR/1gkppDcjBtiVdOFsWhnpBI4x45GsedYthGhhxh3jAxg440plbHTxFtpadbylmnAZxJGBkdfoNQ0gDDw/29eoCksrmcqEswTkAK1NW5GlMQklcQGOcnBwPkeLGJReBK4+DpQsqKhdw9XBDf2Y+3BLyMwcnBZ54CJwArlc8llJE7FLP8U4ggE8RdU1cl9zb9tQnQstt/9I+vc4R7QHHHjh09IJ4mA+bsZFZh8ZdMAjINqTPHdZ0lE+80zIwlhsdoAC4BFWJ74bx1XAaJJw/g5ieelPsF9wziqLtE1rEJyjbvBXVAo5gpP2C9ch5zXpRQP4TDbz7//PPypQE9QBw5csQcGhra1tLS8iDb2WxOGoL1iolGJz/H+Lh3l8/4H7xdECd+FRYDfUlsWHXyCS4P9+UDkRJ0KkWSOH42L87n2gQufbGrA5JKopTKAlOW8igES2kAxV5TU6bQrfKSM69ekigo08z+HBCeOAAT9oMnHv/hAw898ucYiNNd0njnzlvhisnhKIV/1RSnDzaJ8REGKQgqY5gtmLZAF4byeZQSvIKU7D45gAWDKK+glccSoHVt2YaAYKSyIebE1V5QUTbfAD+i4Mzr1Nc38BLqskN6ABuHDh0axAbYhcuQZQScGB+Xr8RYD0wQiLv1r54V4sybHbjQxBMfqHGzouJ5jBWYaQRki4oEElKdC1twxp/CZQxweK7rGacn2MCn8jy0Gb1cluImWIWYb2h0ZNQ1QL6Q/5+/+LP7jgJEUgBJmYr4lNXs6z3/D3ofkJ+f4NGRUIEZnd3v2KL7SJuwoLxUGtQ421Jhp6QRlPuTEJAq5CvmCdEQxytyKKwMBjxYo8CMQEqVhuhMWWJVSh6EkGv6v0m8E8jhvaTWa2hgcNvp06dlFEjNtQFYt377sxueKeQLXRq4v78fiM6R4xcczM++g+tuzjyU5Dqn4DrrNse4/8fhtoGGxBj7TQD+wcq0Uh6PrVJ50LNIU9LGEkH52LK0sCrb0bWvZubd/BAL5A68/torDksU5QagHJmh4eF/0QZg7JzLwnoY8GdEtlgmCE4cpeUsQ1m9Vim4VB5lDsjz56gwVNP2llrqa9oLYtv1wyIZs8QQkIfh+xl4RGdDQXx/9aj4jzWjzj0+pWHyl6pXj3Dj0xs6+Z3t7t68devWso+w9R6gMQtPPP43T357y9Y7ItEo9oKi6B8YEPgIUV6USiAoSb6IlUSyDWdyl5olqTCVdgxC0WgMtme1FERLI7/8JPLUpNXgSGvcFj+6fkSkAcv+BIIfHDBy1jkuYUs/usdTEgpwUHh4ZESWbOMkGNn78q4XUC27d4d4Zam4b9++oa7u03xJIv94hIyAkGINzlwKHEG5aLUpTKwQKiln3lPSM9hngt36aycQhyuhvDNPUqqtyKo2XB404zgFEjwJ8I+fA8oxR1RKUDUBYGBgUH4v5OiRf//X79/19NNPjwKvDD1oStiXevmn+59JpRo+rxk1NzWJhqZG3ZRk8GQq3thTJ94+2ICjTxmC69VC5mZoY93fvG5cXLkqKwOjEvLFrfEFCOIal8lkZvKlW2664XfR4Ynw1DBEDUx4H9l4cNXll9+DJQjVGBxl5degUUYqTuL+uGBZXnRcYoqu0wx3kSK2SDTYYtXqSXH3xmExp5UPQRrDV9LUeixoKnzguqnRglAmEcXiO2YNyq9Ju+//xn0benp6Ar8ZDKKhkWN33XXPqrs3feUNGEF+As8IrL1jjjSEBvKWWlGA6QDRO/wR6l5Vaalq4qpJ6uvrKzP4O8fe+vTXvnLvz4Fctva1MJU8gOP2W28dHbl+7bqetra2W9EOcb2m4V78LtjrCZoYxQsUUeuhAVl6AafXzYsZWIebi/7+ASw17VJC4Cn3y/d+6c7dQOBJHJiqGYAI1ku7Xji5/tYNxVRDww1oy3gug+OFV8wxvKTwauLVU9e9epLgxUj4nypicHDIffvLPRofTT/0jT/56g8xVvEjScpSi3zYzkTq2Z0vfLN93rz7gcC2TKmGlGhpaS7dHeiBC14Gm5Ov0UdGR8XYaOnjcOieHx4c3Lb5y3/4cG9vL5/4Si4RIFctBiCaNMJTT//rvUsuvfS72Avc+IEvUtvb54golkWwmAFcq3VpIoTxSuddJqjnzJzo6+sXlud1OpTP9p3vefT3N37h74HN72KqKk8W0y0BwjCRUP4/d7/wdn1d8mfLV6/+PQgnjcCPDuiCjLnr8PTo3iRJtAv/w33ofG+vGMaHl/qCg1zQbx46fOgLX/2ju59Fk8fdtMoTr1YDEFYa4fDhg72JaPxFeMKaSDS2kANMBcwE4+4c7hLiM/rPE95pVrSCfnlV19fbJ9c6//uMN01m0r98ec+Ln3vs4b86hH4+6NSkPGnUxp2QpUScSGdnZ+uDWx790oKFl9yP/x6jLhQ1DM9NbJC8T6ivr5ef2+khb0lClLSSELyhxv8Hkh9AMw7xJ4a3586eeeSxbd975r0jRxiu8qirWXnSq8SbY9Mlek/ittvuWHz7F+98oLGx6XNw//ogJH6rxw+VYrG4COPNrvz/RDAS4womFQ7jkgMxL7/0NrG++Qhrmu5TaxlZKD46Pja26yf/vuM7O3fu/BCDBERYNvP0cQxAbsSnIZIrVqxo37L1ew/jv7zeHAqFZ31cwiRelvBshJuqwbGxsVf+bftTj+7evfsMxukWgQFOGW6VxoWSUxsiAbdv/Pqf3n/ddWvX/jU+tVtZhXfNQ7ls9vjRIwcf+tvHHv1lOp1mSMuznTM+I3cPYnihDKBpkx6PTD4wJG6//YtzFyxeuGjZshXXtrXNuiGZqr8CywSXX5UT/o/gcGYi/ebg8MAvTr1/+o0zp091/fjH/9wDDCrNrxuo9MdWHDRkqiaLhvmopTYGlwgNIvMtt3y2aeXK5a31TQ2pSDges0OIXQuWOTwymn7v+MmhvXt3czOjojpzpi/IbIPOlPS/fjCt3T2g2QcAAAAASUVORK5CYII="
    }
  },

**Comment by keshamin** [comment]
@zwb124 your code works (except missing backslashes to escape double-quotes). But I believe it should be fixed in built-in `music` widget, because it seems not ready to macOS Catalina.

**Comment by keshamin** [comment]
I think this issue is fixed by https://github.com/Toxblh/MTMR/pull/279 and can be closed.

**Comment by joshuawilson77** [comment]
I've been messing around with this in Big Sur (11.2.3) and I can't get the `music` widget to work. Could this be broken again or am I doing something incorrect. Thanks for any help you can give.

**Comment by zwb124** [comment]
> I've been messing around with this in Big Sur (11.2.3) and I can't get the `music` widget to work. Could this be broken again or am I doing something incorrect. Thanks for any help you can give.

The latest version can support music, so you don't need to write your own script
