### ISSUE TITLE
Custom shell script does not run

### ISSUE THREAD

**Issue by markdon** [Toxblh/MTMR#283]
I've followed every example I can find in presets and issues but can't get this script to run. I'm not even seeing the log at the top output to Console.app. Is there any way to get more debug logging out of mtmr? Can you see something wrong?

Button:
``` json
{
    "type": "staticButton",
    "title": "monitors",
    "action": "shellScript",
    "executablePath":"/Users/mark/projects/displays/displays.sh",
    "shellArguments":"[]"
}
```

/Users/mark/projects/displays/displays.sh:
``` zsh
#!/bin/bash
logger "displays.sh"

displayplacer \
"id:ACF2279A-FB77-0E40-6A1E-2D8A54E66BD1 res:2560x1440 hz:60 color_depth:8 scaling:off origin:(0,0)" \
"id:34CF6778-5B8D-0DE8-96DF-EB47172E8121 res:1792x1120 hz:60 color_depth:8 scaling:off origin:(217,1440)" \
"id:33D760F8-4B26-66A9-FE3B-7A6DB94B50DD res:1440x2560 hz:60 color_depth:8 scaling:off degree:90 origin:(-1440,-504)"
```

**Comment by bobrosoft** [comment]
@markdon `shellArguments` seems wrong... try to just remove it fully

**Comment by FedorZaytsev** [comment]
To get logs you can run MTMR manually from console by calling "/Applications/MTMR.app/Contents/MacOS/MTMR"

**Comment by markdon** [comment]
Thank you both! @bobrosoft removing shellArguments made everything work!

**Comment by markdon** [comment]
It looks like when running MTMR from terminal this script runs ok. When starting MTMR automatically or with Finder the script does nothing. This makes me think the script is running in an environment where displayplacer won't work. 

Launching MTMR automatically with terminal will work fine for me.

**Comment by rrrahal** [comment]
> It looks like when running MTMR from terminal this script runs ok. When starting MTMR automatically or with Finder the script does nothing. This makes me think the script is running in an environment where displayplacer won't work.
> 
> Launching MTMR automatically with terminal will work fine for me.

same thing happening here, have you found a solution or are you still launching from the terminal?

**Comment by markdon** [comment]
Still launching from terminal. I didn't really find a good way to do that automatically. 

I have this in my ~/.zshrc, which tries to start MTMR every time I open a terminal (which I use constantly). Based on some stackoverflow reading 😕It annoyingly leaves a text file in the directory that terminal was opened with.

```
if pgrep -xq -- "MTMR"; then
else
    echo "Starting MTMR"
    nohup /Applications/MTMR.app/Contents/MacOS/MTMR &
fi
```

**Comment by ash14** [comment]
> It looks like when running MTMR from terminal this script runs ok. When starting MTMR automatically or with Finder the script does nothing. This makes me think the script is running in an environment where displayplacer won't work.

You may not have the right `$PATH` set in the context of your script - add a line like
```sh
PATH=$PATH:/usr/local/bin/
```
in your script or use the full path to any executables.
