### ISSUE TITLE
Node js issues

### ISSUE THREAD

**Issue by beavcast** [Toxblh/MTMR#294]
Hi,
first of all, thanks for your amazing job. 

I'm trying to write a "shellScriptTitledButton" with a "source" that is a nodejs simple program that writes a number in the console. But I'm always gettin an error as result in the touchbar component. Someone can help me understand what am I missing? Thanks in advance!

**Comment by FedorZaytsev** [comment]
Can you please post which error you are gettin?

**Comment by beavcast** [comment]
Never mind, I used a static button linking the node version in the executablePath and the arguments in shellArguments. In this way it works. Thanks!
