### ISSUE TITLE
Custom action handler on native actions

### ISSUE THREAD

**Issue by dantebarba** [Toxblh/MTMR#303]
Is there any way to set a custom action handler for a native action?. e.g. I would like to mute when long tapping the decrease volume icon.

reason: to free up a space by removing the mute button

**Comment by dkoenigsberg** [comment]
Would something like this do what you want?

    {
      "type": "staticButton",
      "title":"Volume down",
  "action": "appleScript",
      "actionAppleScript": {
        "inline": "set theOutput to output volume of (get volume settings)\r   set volume output volume (theOutput - 6.25)\r do shell script \"afplay /System/Library/Sounds/Pop.aiff\""
      },
  "longAction":"appleScript",
  "longActionAppleScript":{
  "inline":"set volume 0"
  }
    }

(You'd probably want to include an icon for the button, I'm just putting the code for functionality here.)
If you wanted to toggle mute, you could store the pre-muted volume level it in a file and when unmuting, restore the volume level to the value in the file.

https://stackoverflow.com/questions/18169032/increase-volume-by-1-in-applescript
https://osxdaily.com/2007/04/28/change-the-system-volume-from-the-command-line/

**Comment by dantebarba** [comment]
thats what I was looking for thanks!.

> (You'd probably want to include an icon for the button, I'm just putting the code for functionality here.)

Yeah I'll just have to find the matching icon.
