### ISSUE TITLE
the color of inputsource buttion is black

### ISSUE THREAD

**Issue by huigher** [Toxblh/MTMR#309]
The built-in button inputsource's color is always balck while others is white.Did any body can help to solve this issue?

**Comment by hobo313** [comment]
I am also interested in this.

**Comment by evanswa0606** [comment]
{
        "type": "inputSource",
        "bordered": false,
        "align": "left",
        "title": "TEST",
        "background": "#ff00cc"
}
background is a hexadecimal. You could also use AppleScriptTitledButton and ShellScriptTitledButton for further customizability, but you would have to write the apple scripts on your own. Setting property "bordered" to true would also work, just a grey background.

**Comment by huigher** [comment]
> {
> "type": "inputSource",
> "bordered": false,
> "align": "left",
> "title": "TEST",
> "background": "#ff00cc"
> }
> background is a hexadecimal. You could also use AppleScriptTitledButton and ShellScriptTitledButton for further customizability, but you would have to write the apple scripts on your own. Setting property "bordered" to true would also work, just a grey background.

This is an awesome solution!
