### ISSUE TITLE
When the new release is planned?

### ISSUE THREAD

**Issue by keshamin** [Toxblh/MTMR#311]
Hello! 
I love this application! I see that one of PRs fixed the issue with Music app that Catalina brought. 
I would like to install a fresh version but it seems like it is not released. Is the release planned?
Thanks.

**Comment by Toxblh** [comment]
I hope I'll can to do that today.

**Comment by Toxblh** [comment]
Need to wait few days for renewing my apple account for the sign new app.

**Comment by bobrosoft** [comment]
@Toxblh this one https://github.com/Toxblh/MTMR/issues/305 is working? Or reverted? That's a major issue.

**Comment by Toxblh** [comment]
> @Toxblh this one #305 is working? Or reverted? That's a major issue.

should work. Doesn't change the part
