### ISSUE TITLE
Sort items based the Json order

### ISSUE THREAD

**Issue by danillos** [Toxblh/MTMR#33]
Items without a defined align are randomly sorted by Reload Preset

**Comment by joebp2** [comment]
I have the same problem. Thanks for reporting.

**Comment by joebp2** [comment]
You can sort them yourself by editing the JSON document.
I added "align": "right" to the previous, play and next buttons and they stick in place from the right side of the bar. 

`{ "type": "previous", "width": 44, "align": "right" },
  { "type": "play", "width": 44, "align": "right" },
  { "type": "next", "width": 44, "align": "right" },
  { "type": "weather","refreshInterval": 600, "icon_type": "images", "units": "imperial", "api_key": "72b409a09c93c76b93a6aa5b76e3c315" },
  { "type": "currency", "from": "BTC", "to": "USD" },
  { "type": "sleep", "width": 44 },
  { "type": "mute", "width": 40, "align": "right" },
  { "type": "volumeDown", "width": 34, "align": "right" },
  { "type": "volume", "width": 60, "align": "right" },
  { "type": "volumeUp", "width": 34, "align": "right" },
  { "type": "battery", "align": "right" },
  { "type": "timeButton", "align": "right" }`
