### ISSUE TITLE
Connect to Bluetooth Device

### ISSUE THREAD

**Issue by siroger** [Toxblh/MTMR#332]
Here is a script I wrote to connect/disconnect my apple airpods...  really handy for switching between phone and macbook:
Be sure to replace YOUR NAME with whatever yours are called.

I would like to add this icon to the button : 🎧.  , does anyone know how to do that?

`{
  "type":"staticButton",
  "action": "appleScript",
  "title": "Headphones",
  "align": "right",
  "actionAppleScript": {
       "inline": "  activate application \"SystemUIServer\"\r       tell application \"System Events\"\r         tell process \"SystemUIServer\"\r           set btMenu to (menu bar item 1 of menu bar 1 whose description contains \"bluetooth\")\r           tell btMenu\r             click\r             tell (menu item \"YOUR NAME’s AirPods Pro\" of menu 1)\r               click\r                 click menu item 1 of menu 1\r             end tell\r           end tell\r         end tell\r       end tell\r       ",
  },
},`

**Comment by siroger** [comment]
Found the solution:
`"title": "🎧 ",`
For some reason I had to add a space after the emoji.

**Comment by siroger** [comment]
Final update to appearance:

  "type":"staticButton",
  "action": "appleScript",
  "bordered": false,
  "background":"#fff",
  "width": 30,
  "title": "🎧 ",

**Comment by Rahulsharma0810** [comment]
Your Script not working with the airpod name. 

```
  {
    "type": "staticButton",
    "action": "appleScript",
    "align": "right",
    "title": "🎧 ",
    "background":"#fff",
    "actionAppleScript": {
      "inline": "activate application \"SystemUIServer\"\r tell application \"System Events\"\r tell process \"SystemUIServer\"\r set btMenu to (menu bar item 1 of menu bar 1 whose description contains \"bluetooth\")\r tell btMenu\r click\r tell (menu item \"Rahul’s AirPods Pro\" of menu 1)\r click\r click menu item 1 of menu 1\r end tell\r end tell\r end tell\r end tell\r "
    }
  },
```

Can you help what's wrong?

**Comment by siroger** [comment]
Check in your Bluetooth menu to get the exact name of your device.  
I haven’t tested it, but it may work with just the starting few letters.....

menu item \"Rahul"
or

menu item \"Rahul*” 

Just a suggestion. 


On 19 Jan 2021, at 13:10, Rahul sharma <notifications@github.com> wrote:

﻿
Your Script not working with the airpod name.

  {
    "type": "staticButton",
    "action": "appleScript",
    "align": "right",
    "title": "🎧 ",
    "background":"#fff",
    "actionAppleScript": {
      "inline": "activate application \"SystemUIServer\"\r tell application \"System Events\"\r tell process \"SystemUIServer\"\r set btMenu to (menu bar item 1 of menu bar 1 whose description contains \"bluetooth\")\r tell btMenu\r click\r tell (menu item \"Rahul’s AirPods Pro\" of menu 1)\r click\r click menu item 1 of menu 1\r end tell\r end tell\r end tell\r end tell\r "
    }
  },
Can you help what's wrong?

**Comment by siroger** [comment]
This stopped working on BigSur,   here is an update:

`  
  "actionAppleScript": {
       "inline": "tell application \"System Events\"\r      tell process \"ControlCenter\"\r          set bt to (first menu bar item whose title is \"Bluetooth\") of menu bar 1\r              click bt\r              set btCheckbox to checkbox 1 of scroll area 1 of group 1 of window \"Control Centre\" whose title contains \"AirPods Pro\"\r                set btCheckboxValue to value of btCheckbox\r            tell btCheckbox to click\r              tell bt to click\r      end tell\r end tell\r  ",
  },
},
`
