### ISSUE TITLE
Show music info when paused

### ISSUE THREAD

**Issue by jrsall92** [Toxblh/MTMR#339]
I've noticed that when I pause the music I'm losing the song information from the bar. I have to resume the track to get it back again. I'd like to be able to retain that information as long as the app is running. I have this issue with Spotify, I don't know if it's the same for Music as well, I don't use it.

**Comment by jeroenseegers** [comment]
I created the following AppleScript snippet to keep the song information displayed while the song is paused.

```applescript
if application "Spotify" is running then
    local title

    set title to "Nothing playing"

    tell application "Spotify"
        if player state is in {playing, paused} then
            set title to (get artist of current track) & " - " & (get name of current track)

            if player state is paused then
                set title to title & " (paused)"
            end if
        end if
    end tell
end if

return " " & title
```
