### ISSUE TITLE
MTMR not opening at all

### ISSUE THREAD

**Issue by b00071518** [Toxblh/MTMR#341]
I have macOS 10.15.5 and MTMR 0.26.1

I opened the app first time and it was working, then I started to make a few changes in the code and testing.

I accidentaly typed a wrong value for a refreshInterval (I put a double instead of int).

When I hit save, the MTMR Touch Bar crashed and the app closed and disappeared from the menu bar.

So I command-Z the error I made and saved the json to its original format and tried opening the app again, only this time it refused to open.

I restarted my Mac, uninstalled and installed again, ctrl-right-click-open, and nothing works.

Please help I really love MTMR.

**Comment by Jarown** [comment]
Removing the items.json file solved the problem for me (make a backup first):
`rm /Users/[user]/Library/Application\ Support/MTMR/items.json`

I read about removing just the `nightShift` configuration, but that item wasn't present in my json.
