### ISSUE TITLE
Problem creating applescript for Zoom.us 

### ISSUE THREAD

**Issue by pierreolivierblais** [Toxblh/MTMR#346]
I am having trouble (no experience) creating the inline applescript. 

I was able to create a script that triggers the Mute/Unmute button : 
```
if application "zoom.us" is running then
	tell application "zoom.us"
		activate
		tell application "System Events"
			keystroke "a" using {shift down, command down}
		end tell
	end tell
end if
```

I also wanted to change the icon of the button based on the mute status :

```
 {
        "type": "appleScriptTitledButton",
        "source": {
          "inline": "if application \"zoom.us\" is running then\ntell application \"System Events\"\ntell application process \"zoom.us\"\nif exists (menu item btnTitle of menu 1 of menu bar item \"Meeting\" of menu bar 1) then\nset val to {\"title\", \"micon\"}\nelse\nset val to {\"title\", \"micoff\"}\nend if\nend tell\nend tell\nelse\nset returnValue to \"\"\nend if\n"
        },
        "refreshInterval": 1,
        "image": {
          "base64": "iVBORw0KGgoAAAANSUhEUgA..."
        },
        "alternativeImages": {
          "micon": {
            "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEISURBVHgB7ZaNDYIwEIUP4wDECRzBDcRNGMERmESdQBMH4GcBHUEnACegXuMjNk2AFluNSb/k0lCOe70j7ZUoENAQQizZCrZGvDjKOfIJRDtBldqrOAc/iX5ym1iRjbOMPvC6iaJoQT8QFiw8I0OMHV0ThIOwN+ZjDryDui0nyCEmGbewmO0x5CgX2R2h5ED4jnHFdh3wO7Ml2jfT4dVnyKJAk6j7mgTbAc87+hQOEitiGQRks2jRqXLMZc47FQdKISTZs23wP+WiElRDwGdLLpEBe8qsljslH6CkMuOLInhDmWP6BhDLaCKjB4gmRq6wvQgk9N6ra4wVxpIvAiUZYpWxRkWBf+AJHoxYMncV6uwAAAAASUVORK5CYII="
          },
          "micoff": {
            "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAG5SURBVHgB7ZVbTsJAFIbPVN5t3YDICowbsPQN39yBcQXGBUhxA8oGFFZgYoyXxEB980ncgV2B1A0w/odOQ6lQZtr6QviTH9rO5Zszt0O00bpLkKGklHX83cL7sA3fwedCiPBPXdeniN738DTgVyd4aSRlFhlIQUewq6CsY/hDlS2D1rN9GYGhqxQwLQe+yYF+YXK9dAOjqUZUMqd4jOneWQZ1gufwv8CSmh1LB8oyneo89XWhVYJ7UbN1qQutCmwMrQLcLwJl1ai4GOoDOjSFsopGXAqqBcYJEsrJJ17Tzhx0q+bZw6cLMpBOxBNlvrG6mTUNp9DXhzaeT9QAWd9VgMPpr6Q6oN3MRmomUPie4jt81iZHOpurD+9GXutnDpqKFB7DZ7Cv2nyu6nTllSknEzvyjpw5qLA8e/DIa8qZibPVqRpAWw3iYFGa1AYvvPDjSPGNAnib4rzMQJebUJybr2mFhBEURwa7N5nerMYK2iMNWYbQSFUZpaqHMI4XNXShLKELzV4OODL+tAMhfCqgmgk0Px2XAGtE6tLsrB6qwfjqPUD0ARUBG2aZNyqh7AUi86AqooA2KqBfgO8OPC0eEHcAAAAASUVORK5CYII="
          }
        }
      }

```
But I get an error. 

Is there anyone here with expertise that could help me out?

-- Also, is there an easy way to convert Applescript to a oneliner? 

Thank you in advance!

**Comment by msaktor** [comment]
I have something that kinda works, I will try to fine tune it to display if Zoom is currently muted or not, right now the button always say "Mute". Here's the code:

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "inline": "return {\"Mute\"}"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"System Events\"\n\tkey code 0 using {shift down, command down }\nend tell"
    },
    "width": 64
  },
```

**Comment by msaktor** [comment]
Nailed it!

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "inline": "if application \"zoom.us\" is running then\ntell application \"System Events\"\n \ttell application process \"zoom.us\"\n \t\tif menu item \"Mute audio\" of menu 1 of menu bar item \"Meeting\" of menu bar 1 exists then\n \t\t\treturn {\"Mute\"}\n \t\telse\n \t\t\treturn {\"Unmute\"}\n \t\tend if\n \tend tell\n end tell\nelse\nreturn\"\"\nend if"
    },
    "refreshInterval": 1,
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"System Events\"\n\tkey code 0 using {shift down, command down }\nend tell"
    },
    "width": 64
  },
```

**Comment by rafaeldcf** [comment]
Here you have my preset for Zoom.us (working with v.5.4.1)
`{
        "type": "appleScriptTitledButton",
        "source": {
            "inline": "if application \"zoom.us\" is running then\r\tset val to {\" \", \"no_meeting\"}\r\ttell application \"System Events\"\r\t\ttell application process \"zoom.us\"\r\t\t\tget every menu bar\r\t\t\ttell menu bar 1\r\t\t\t\tif menu bar item \"Meeting\" exists then\r\t\t\t\t\ttell menu bar item \"Meeting\"\r\t\t\t\t\t\ttell menu \"Meeting\"\r\t\t\t\t\t\t\tif menu item \"Mute Audio\" exists then\r\t\t\t\t\t\t\t\tset val to {\"UnMuted\", \"unmuted\"}\r\t\t\t\t\t\t\telse\r\t\t\t\t\t\t\t\tset val to {\"Muted\", \"muted\"}\r\t\t\t\t\t\t\tend if\r\t\t\t\t\t\tend tell\r\t\t\t\t\tend tell\r\t\t\t\tend if\r\t\t\tend tell\r\t\tend tell\r\tend tell\r\treturn val\relse\r\tset val to {\" \", \"off\"}\rend if"
        },
        "action": "appleScript",
        "actionAppleScript": {
            "inline": "if application \"zoom.us\" is running then\r\tset val to {\"title\", \"no_meeting\"}\r\ttell application \"System Events\"\r\t\ttell application process \"zoom.us\"\r\t\t\ttell menu bar 1\r\t\t\t\tif menu bar item \"Meeting\" exists then\r\t\t\t\t\ttell menu bar item \"Meeting\"\r\t\t\t\t\t\ttell menu \"Meeting\"\r\t\t\t\t\t\t\tif menu item \"Mute Audio\" exists then\r\t\t\t\t\t\t\t\tclick menu item \"Mute Audio\"\r\t\t\t\t\t\t\t\tset val to {\"title\", \"unmuted\"}\r\t\t\t\t\t\t\telse\r\t\t\t\t\t\t\t\tclick menu item \"Unmute Audio\"\r\t\t\t\t\t\t\t\tset val to {\"title\", \"muted\"}\r\t\t\t\t\t\t\tend if\r\t\t\t\t\t\tend tell\r\t\t\t\t\tend tell\r\t\t\t\tend if\r\t\t\tend tell\r\t\tend tell\r\tend tell\r\treturn val\relse\r\ttell application \"zoom.us\" to activate\rend if"
        },
        "refreshInterval": 1,
        "alternativeImages": {
            "unmuted": {
                "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEISURBVHgB7ZaNDYIwEIUP4wDECRzBDcRNGMERmESdQBMH4GcBHUEnACegXuMjNk2AFluNSb/k0lCOe70j7ZUoENAQQizZCrZGvDjKOfIJRDtBldqrOAc/iX5ym1iRjbOMPvC6iaJoQT8QFiw8I0OMHV0ThIOwN+ZjDryDui0nyCEmGbewmO0x5CgX2R2h5ED4jnHFdh3wO7Ml2jfT4dVnyKJAk6j7mgTbAc87+hQOEitiGQRks2jRqXLMZc47FQdKISTZs23wP+WiElRDwGdLLpEBe8qsljslH6CkMuOLInhDmWP6BhDLaCKjB4gmRq6wvQgk9N6ra4wVxpIvAiUZYpWxRkWBf+AJHoxYMncV6uwAAAAASUVORK5CYII="
            },
            "muted": {
                "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAG5SURBVHgB7ZVbTsJAFIbPVN5t3YDICowbsPQN39yBcQXGBUhxA8oGFFZgYoyXxEB980ncgV2B1A0w/odOQ6lQZtr6QviTH9rO5Zszt0O00bpLkKGklHX83cL7sA3fwedCiPBPXdeniN738DTgVyd4aSRlFhlIQUewq6CsY/hDlS2D1rN9GYGhqxQwLQe+yYF+YXK9dAOjqUZUMqd4jOneWQZ1gufwv8CSmh1LB8oyneo89XWhVYJ7UbN1qQutCmwMrQLcLwJl1ai4GOoDOjSFsopGXAqqBcYJEsrJJ17Tzhx0q+bZw6cLMpBOxBNlvrG6mTUNp9DXhzaeT9QAWd9VgMPpr6Q6oN3MRmomUPie4jt81iZHOpurD+9GXutnDpqKFB7DZ7Cv2nyu6nTllSknEzvyjpw5qLA8e/DIa8qZibPVqRpAWw3iYFGa1AYvvPDjSPGNAnib4rzMQJebUJybr2mFhBEURwa7N5nerMYK2iMNWYbQSFUZpaqHMI4XNXShLKELzV4OODL+tAMhfCqgmgk0Px2XAGtE6tLsrB6qwfjqPUD0ARUBG2aZNyqh7AUi86AqooA2KqBfgO8OPC0eEHcAAAAASUVORK5CYII="
            },
            "off": {
                "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAB6gAwAEAAAAAQAAAB4AAAAAOXtaBgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABoBJREFUSA19V8+PFEUUftXdM7Mzy+zKAoI/QkjYhOhBTAxEjD8TwXgVhqOLmKwHo0cRPbgHEkPiHyB7MCwHYxg5mYBxE4MeuHgiwQO6itEYIMACO7uz86O7n9/3qnu3J7trZWqq6tV73/eq6r3qbidZmZrSYGrKpRw2zuumoCsNFTmI4biojKEdQa2jllADcfhngRIK7fqoLdQFzM2jnYPKbFqRZvOoW8RYihxmDqIQkwknj87ohDg9XR522xWgaQxstIpZBTz7+Ed11kMfGE4c/wPU0LcBW8h6S3obKifOT7gZWuZcruhF45yeqdRlsrcEuFg6QAaUonpcjI2EAGuLctJ8xBxVU4xTF8lQeVik25Lp5tvuPdqRE3O+HD6rZ2qbZbI9L20niu10Jc32MdeBDCKs0OWrXZ3xPa5+tUARA+3Di7g25qrt+zJ94ZgnN8XDX+lEZVTOdh7qMgQVEARkWIXYqGfAfpILNocGzfwhaIrpztCo1LoP5diF427GMZDils4FIc401j6MudJB6wJvgaog/f+ukav2g8iVkkRvR3U3HsWL0ijX3HYEQQcrHVIU2wZgefZBqvU8yvXX0nvb1J9PKYm1w6DtgTNCtB5MfbQGtlDoEpyVZsFGx5mxYA8lQV2NlqK9BZxpYj0EDIwLnBHIxtM+willBPtC0jJGJTAzMli871kfm6I4T8qqSBuqtJB2BKAjFcgoX4ashzH1stUEKbNdZTyC4hgzGA5h3gdtBMy7XadXsflbgYatwM3iiYgBKHMHuPIngPYiHPcgZVroP1JS96Dv9Nt7Ii9Btq3snXcWNs6l4EpVxyKsdIQDHgOvH3p7s+N03xaRL/Y7Ga2pi5PAFkg2BAogMGQLmyU4eOmayrkbIi9uFrl0z+lB3HM/vunkyh8q3/ylcMpJj+BcQGK7OxIBpG4DSwfeFipXlkU+2OnkuXHugm1U3tI676+0T+90GlxU+fRXlQ93OfnoDXFPbBW5syB67TeRp4a5k+Y2iK1f54qRPuaOUfDwwS2R8XEjfOX1t16hvFoW99oe0eP3RU69Ja5e9cr8ZzVM2yFi2ZmWIrRZNHtlkrIyUlkIzG6R2MaQ2SKohEKyd/b7NsbRRTiyNEUQIpcIgNZwqIthQGIUBAuUePNYqEJWzKLMJSpaWRmvdHw6VZgGhcI4oHfksOrnjBHplI+o5BWsLQBs2KXtINeAqkFnmAVi0wlMwNUWSO3IzWrAUzPIxAMEHCTYyk6PD6RCoTK3OMNmm/OQGGnlJ5n8EJgT83g0stgZcx79oqH1cxla3HDu619EF5bUzhciXzLsFVtcCABLAzw3cDkxvvxZ9BEPB6oiF39Xuf4P6URCXCJcCp1Yr1KnXHL6JdLp5HnVf+94O/M2RhSTnIFm7Mxj7UeAajmHh0NimxC0EYVbcdvcaIt89p3ou8+LPLmFvADwz+GV7SSO3dHAmr2qcmC7yPc3Ve6CfPKFQK7fUnkcWDG2kroWRSFcV9eKEPILYSjbOEfPSbGEq2/XkMjfiyqHLkCMEKzAxS6szQOoUZk5EGGP+7g7d+DV4ZmayKO4Pm/hAnq9mcqzeEvbCxnvbHoLGw3RISfg7MVsNzA9MQS87JegPAawIztAiLzM8xpThcJNxFEAjMCLsFnoiWxCDh95zGPQlrvCFaPkHPMRom4OTPsgYmxZoRKV2wBiNWAir1Motncb2PD86TRXmK+SHhkw5xnjVEjdXIAEmCUeyHC6PHj2cZmjJSgrU4W30UqN+eDw4z7bTJcOkyS3Q5cC3l4ABTY5KHI6G6S1sNlrp7ckCIeQV32snIdvNuaEqVK9WPx8UeLBIbHoBY+RcREWUs6wwUEucgaX33cIIf04QjBhpQhABDszgNEGeqsAyZ2wlvKNZMwazpmOYYAU7qj0jQNc5OSuWHnl8/hMZSSc7D6MEZOIY7zewtx+prDOG6S3LPxb0GdjQ+YfdlFcvzIa1roLyfRPJyN7t8Zni72wCwXdB8l0aTiq4tlRwoo78LKHiisAQQ2fbRX0ZePKI07MhrbAIFZpGKTAzknJaX41GviEafpPmJdPxROAPh1VI/uEsU8XEtnWIpLyXUAk2NryVSKkHb5b7DMGqPYpgzZejm8jRU78/Ek0Q/2cy4gpoBf5R9urU3jXDpOGk/QQIHYD23+0qdaBjxcHSwqa5YVPXb6T20cbfMJHm+LFJ/ghSsLm5am1H23/AWYJyqJQRoKsAAAAAElFTkSuQmCC"
            },
            "no_meeting": {
                "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAAAXNSR0IArs4c6QAAAIRlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAB6gAwAEAAAAAQAAAB4AAAAAOXtaBgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAABoBJREFUSA19V8+PFEUUftXdM7Mzy+zKAoI/QkjYhOhBTAxEjD8TwXgVhqOLmKwHo0cRPbgHEkPiHyB7MCwHYxg5mYBxE4MeuHgiwQO6itEYIMACO7uz86O7n9/3qnu3J7trZWqq6tV73/eq6r3qbidZmZrSYGrKpRw2zuumoCsNFTmI4biojKEdQa2jllADcfhngRIK7fqoLdQFzM2jnYPKbFqRZvOoW8RYihxmDqIQkwknj87ohDg9XR522xWgaQxstIpZBTz7+Ed11kMfGE4c/wPU0LcBW8h6S3obKifOT7gZWuZcruhF45yeqdRlsrcEuFg6QAaUonpcjI2EAGuLctJ8xBxVU4xTF8lQeVik25Lp5tvuPdqRE3O+HD6rZ2qbZbI9L20niu10Jc32MdeBDCKs0OWrXZ3xPa5+tUARA+3Di7g25qrt+zJ94ZgnN8XDX+lEZVTOdh7qMgQVEARkWIXYqGfAfpILNocGzfwhaIrpztCo1LoP5diF427GMZDils4FIc401j6MudJB6wJvgaog/f+ukav2g8iVkkRvR3U3HsWL0ijX3HYEQQcrHVIU2wZgefZBqvU8yvXX0nvb1J9PKYm1w6DtgTNCtB5MfbQGtlDoEpyVZsFGx5mxYA8lQV2NlqK9BZxpYj0EDIwLnBHIxtM+willBPtC0jJGJTAzMli871kfm6I4T8qqSBuqtJB2BKAjFcgoX4ashzH1stUEKbNdZTyC4hgzGA5h3gdtBMy7XadXsflbgYatwM3iiYgBKHMHuPIngPYiHPcgZVroP1JS96Dv9Nt7Ii9Btq3snXcWNs6l4EpVxyKsdIQDHgOvH3p7s+N03xaRL/Y7Ga2pi5PAFkg2BAogMGQLmyU4eOmayrkbIi9uFrl0z+lB3HM/vunkyh8q3/ylcMpJj+BcQGK7OxIBpG4DSwfeFipXlkU+2OnkuXHugm1U3tI676+0T+90GlxU+fRXlQ93OfnoDXFPbBW5syB67TeRp4a5k+Y2iK1f54qRPuaOUfDwwS2R8XEjfOX1t16hvFoW99oe0eP3RU69Ja5e9cr8ZzVM2yFi2ZmWIrRZNHtlkrIyUlkIzG6R2MaQ2SKohEKyd/b7NsbRRTiyNEUQIpcIgNZwqIthQGIUBAuUePNYqEJWzKLMJSpaWRmvdHw6VZgGhcI4oHfksOrnjBHplI+o5BWsLQBs2KXtINeAqkFnmAVi0wlMwNUWSO3IzWrAUzPIxAMEHCTYyk6PD6RCoTK3OMNmm/OQGGnlJ5n8EJgT83g0stgZcx79oqH1cxla3HDu619EF5bUzhciXzLsFVtcCABLAzw3cDkxvvxZ9BEPB6oiF39Xuf4P6URCXCJcCp1Yr1KnXHL6JdLp5HnVf+94O/M2RhSTnIFm7Mxj7UeAajmHh0NimxC0EYVbcdvcaIt89p3ou8+LPLmFvADwz+GV7SSO3dHAmr2qcmC7yPc3Ve6CfPKFQK7fUnkcWDG2kroWRSFcV9eKEPILYSjbOEfPSbGEq2/XkMjfiyqHLkCMEKzAxS6szQOoUZk5EGGP+7g7d+DV4ZmayKO4Pm/hAnq9mcqzeEvbCxnvbHoLGw3RISfg7MVsNzA9MQS87JegPAawIztAiLzM8xpThcJNxFEAjMCLsFnoiWxCDh95zGPQlrvCFaPkHPMRom4OTPsgYmxZoRKV2wBiNWAir1Motncb2PD86TRXmK+SHhkw5xnjVEjdXIAEmCUeyHC6PHj2cZmjJSgrU4W30UqN+eDw4z7bTJcOkyS3Q5cC3l4ABTY5KHI6G6S1sNlrp7ckCIeQV32snIdvNuaEqVK9WPx8UeLBIbHoBY+RcREWUs6wwUEucgaX33cIIf04QjBhpQhABDszgNEGeqsAyZ2wlvKNZMwazpmOYYAU7qj0jQNc5OSuWHnl8/hMZSSc7D6MEZOIY7zewtx+prDOG6S3LPxb0GdjQ+YfdlFcvzIa1roLyfRPJyN7t8Zni72wCwXdB8l0aTiq4tlRwoo78LKHiisAQQ2fbRX0ZePKI07MhrbAIFZpGKTAzknJaX41GviEafpPmJdPxROAPh1VI/uEsU8XEtnWIpLyXUAk2NryVSKkHb5b7DMGqPYpgzZejm8jRU78/Ek0Q/2cy4gpoBf5R9urU3jXDpOGk/QQIHYD23+0qdaBjxcHSwqa5YVPXb6T20cbfMJHm+LFJ/ghSsLm5am1H23/AWYJyqJQRoKsAAAAAElFTkSuQmCC"
            }            
        },`

**Comment by kevbost** [comment]
![image](https://user-images.githubusercontent.com/1672548/120075293-ed42c680-c05d-11eb-9bce-567e55e21450.png)
![image](https://user-images.githubusercontent.com/1672548/120075439-81149280-c05e-11eb-9831-9562bf7c6d13.png)

Zoom does have TouchBar defaults for mute/unmute, but it's all the way back in the default system touchbar.

Building on @rafaeldcf's solution, I opted to not show the zoom app icon. This is two buttons that control `Muted`, `UnMuted`, `Visible`, `Hidden` (cameraon, cameraoff).

# In order for this to work for you, 

I opted to have AppleScript fire keypresses.

- You'll need to update Zoom keyboard shortcuts:
`Zoom -> Preferences -> Keyboard Shortcuts -> Enable Global Shortcuts` (!important)
- `Mute/Unmute My Audio` -> `command + option + control + shift + M`
- `Start/Stop Video` -> `command + option + control + shift + V`

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "inline": "if application \"zoom.us\" is running then\nset val to {\"\", \"\"}\ntell application \"System Events\"\ntell application process \"zoom.us\"\nget every menu bar\ntell menu bar 1\nif menu bar item \"Meeting\" exists then\ntell menu bar item \"Meeting\"\ntell menu \"Meeting\"\nif menu item \"Mute Audio\" exists then\nset val to {\"UnMuted\", \"unmuted\"}\nelse\nset val to {\"Muted\", \"muted\"}\nend if\nend tell\nend tell\nend if\nend tell\nend tell\nend tell\nreturn val\nelse\nset val to {\"\", \"\"}\nend if\n"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"System Events\" to keystroke \"M\" using {option down, shift down, command down, control down}"
    },
    "refreshInterval": 1,
    "alternativeImages": {
      "unmuted": {
        "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsSAAALEgHS3X78AAABhklEQVRIicVW0XGDMAwVvfyHDcIGoRswAiN4BLpBRmAERkgnaLoB2YBuQCZQzz258flsWcJc++58GCHrISEkVYgI/4GXAs6W1jZYjxWrRsQLIq74xEqyWmNLSzxjGrPGlibUFwA4M8/PpCOCJrkWADhldL4AoNmbWKpYSZRKstrilYj8JUKpx3cAWANZ9xfEUZsSpYOUNYE3AJi3HOSIWwrbyOjYDK4D2Y2uA+3jL8b85K46DXQvBdAZJBtR+5zHR7qGHvl4T3jkzhzjx8q/8eiFVgUJMdeBPiKyStK1uALyCIjvOWOeTrZscsQuhCdBdjuMROqayWdSk8nq3sti1/ImJrMn0rl6siFlX9N/nWETyGeShS+2cMNBjrgNpo0bIjYRvYae+ehLJxATCetMIZ0SU4nJ2ZWOKi2FLocl5+nWmcsEyeN/AqMZ+LTEbnUeabfFhqZk2kLS094vEMZr/ldpm9QMAitX9AmPTFP5hWbmWnbS+YHGY+tJrvjbMIczWDHxfgCAb8D/FLMK+ZVAAAAAAElFTkSuQmCC"
      },
      "muted": {
        "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsSAAALEgHS3X78AAACo0lEQVRIicVXPWzTQBR+bqjUqNBYFiwgZA/JwkBhRCwZGFAXmFg64A7MpANiQSIIFiaCxMCCmuxFCkIwm5XJnb1chYqQaCIHCTlIRIde9S49vzi2L63EJ51iP9/dd+/d+4slpYT/gaUTcF6jsRhQY4NhSynbUspYHiMmmW2ylylxKOcjNNnLxNRtAFjP+b5Oc0oh5VxDr9GkxSH+OiKKtU0EALgFm+4DgLcIMRLV6HUPAHxHRCG9l3V/q8wkbuqa9oymC4Ze427O+utEpI9yp2Ma+wDQYQdAvHZE9DBjPVolZrKmMTGRY2z2+X2euXHx8Nzb3fNW7ULhngsRE7kNAF0AuJOaXK2M196/W6lcualE2+SIOoIyxJnhhN7siAjv9pkul8lkZbThw7j3Ykwij0yrD4VWXmYrzNUUYn1+78u3G4dnX/ayTG8R6SsAGAGAvRAxHJs+4AlkyVv9vvrk0cflW5s/NHGbxlPtIEbEXTr51GuHXgM9nns3atVyRNRl5LnEeSnzPmk5zUSOiPAgW0SmgFew8/v5g59akikMqTyNVRabSYMUcl1ueutS9Zs8SK46IhKaTxhrrMLC5RpQGkXZB10uD5LLYMH+36+fFOmXeZvnEet31uEftZDbTn2QsPbrXguSN4//sD1SKPLqUDNnD4tG1iQyfcBDzqpWPstkssmq3BGK6rGvOdKMsymQ6T1uWplMNvDwdDAjjRX5DpOp4hBS6BiHXNkuM7NwaIfw9ZxNpbTLTe+IaOrhZVsfZcot7skkT7U8joj65PV7mniUWmXY7KnR1Fq+5rx5A7duD9x6Z+DWg4FbT80zaejR3Kob8cjZgLxd0HM/o0xmwoQ4zuhMOOZWIw6T9lac0pwjmGiMmhT9ZUEzzySLkxKfHgDgH3+F/T+1ofxbAAAAAElFTkSuQmCC"
      }
    }
  },
  {
    "type": "appleScriptTitledButton",
    "source": {
      "inline": "if application \"zoom.us\" is running then\nset val to {\"\", \"\"}\ntell application \"System Events\"\ntell application process \"zoom.us\"\nget every menu bar\ntell menu bar 1\nif menu bar item \"Meeting\" exists then\ntell menu bar item \"Meeting\"\ntell menu \"Meeting\"\nif menu item \"Stop Video\" exists then\nset val to {\"Visible\", \"cameraon\"}\nelse\nset val to {\"Hidden\", \"cameraoff\"}\nend if\nend tell\nend tell\nend if\nend tell\nend tell\nend tell\nreturn val\nelse\nset val to {\"\", \"\"}\nend if\n"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline": "tell application \"System Events\" to keystroke \"V\" using {option down, shift down, command down, control down}"
    },
    "refreshInterval": 1,
    "alternativeImages": {
      "cameraon": {
        "base64": "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsSAAALEgHS3X78AAAAwklEQVRIie2W4QnCMBBGn9L/dgM7QkeoG+gGjuAodYM6gd3AjuAIukGd4OQghVIIFdok/rgHCYRc8iCE5NuICCnYJrGaOCbZyHUGigXuzrXf0FstIq2sw9HtN9u0K1aSKp1HmItI42rqQVwFFusp9JO6MuTlyoEauAO76VzmWbSUCmiAvW+fUOLHXIE9mSY28d+LD8A7hVi/xxK4xhYrPXABTsBnOqfiV0C50rqAcXNjPYVnsiAwztVRo48FehOHAfgC5q7RL1AZjnkAAAAASUVORK5CYII="
      },
      "cameraoff": {
        "base64": "iVBORw0KGgoAAAANSUhEUgAAAB8AAAAeCAYAAADU8sWcAAAACXBIWXMAAAsSAAALEgHS3X78AAACpUlEQVRIie1XTWgTQRT+EgTTHtw4KHgw2x6yeNMcPHjRrKBQQUyqFPSk0qOHpl56E8Wbl8afexuhePIP7cVL04OCoFgFq7AH4wqCaNbdWLKmTbplwps4jYnJpiG5+GBgefNmvjfz3vfmbcDzPPRLgn1D7ju4pWpJS9U8S9WWLFWL9RQcwCx9HwCQtVTtQq/AA/lINAsgLiu3Hd77dMfcwmufez0CsOQXPEynT8gTwf07HWVuXgkou/3sN0pOtCVBZho2M40kgGvygvV3PxX70JFS+eW8H/BUE704oA0gXdNynouRj0T1fCRq5yNRTx7uzHXXa0+y8n40dM/z7LrVMT63iWrMNHj8eca/lfXFK5nQr0unHM/57ucWwnTKBQBKg7kquM6zXCiYaeSYaXAHMrL12pMPijM28qOy/Lwd4Bgl38S/jMTJ42Rc4zkzDU65iwAcoVv/WNjljI67q/dvuS3A3wAYauWhfO1DtKjGc2Yas3Qzn2tWbmVgZfL2wMrUOavV5n7AhcxQZoowiBt5LBut3nvF7BMHrfUvy10F53Ke8iBGDjSm43uH2cfP/PZJx5bgEOUWQFIomGlcBXBUzgMUy6HCWArunalSN8FBFHkoF4ZmdHRvPNheOBvfY6lauFvgQiaa0PGmbFR+8XUfZ02bdPT1nnM65ij7QU6k6unIWeMkxott0NF3M6FQxarVcImOf8JQqgy2Q8dOO5lper1kOup+6biVNirRhI6TslGVjsdOu2vP7hZJ5VD4wLvXYQCftuCEQ2EQHREsVdPpZjY9KKHUyW+Dl6dHRNMhWue/upkOJCOXZqJcluqFLIu8dvCbkvt2vnC4Q2CbTpqrn7BULd3gdVtkpqH35KeBmtK0FAaHmUa4J317AzpWw/P/d6n3AmAD2idmpy5gS0YAAAAASUVORK5CYII="
      }
    }
  },
```
