### ISSUE TITLE
Support comments inside of the Json

### ISSUE THREAD

**Issue by danillos** [Toxblh/MTMR#35]
Currently when is added `\\` it shows as a `bad preset`

**Comment by ad** [comment]
No, comments of the form //… or /*…*/ are not allowed in JSON.
This answer is based on:
http://www.json.org
RFC 4627: The application/json Media Type for JavaScript Object Notation (JSON)
RFC 7159 The JavaScript Object Notation (JSON) Data Interchange Format - Obsoletes: 4627, 7158

**Comment by danillos** [comment]
@ad Good point but JSON wasn't created to be used as a configuration file too.

I don't see why not support it, a configuration file without comments is hard to do tests and doesn't allow add comments to explain the configurations.

See sublime configuration file:

```
// Place your settings in the file "Packages/User/Preferences.sublime-settings",
// which overrides the settings in here.
//
// Settings may also be placed in syntax-specific setting files, for
// example, in Packages/User/Python.sublime-settings for python files.
{
    // Sets the colors used within the text area
    "color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",

    // Note that the font_face and font_size are overridden in the platform
    // specific settings file, for example, "Preferences (Linux).sublime-settings".
    // Because of this, setting them here will have no effect: you must set them
    // in your User File Preferences.
    "font_face": "",
    "font_size": 10,

    // Valid options are "no_bold", "no_italic", "no_antialias", "gray_antialias",
    // "subpixel_antialias", "no_round" (OS X only), "gdi" (Windows only) and
    // "directwrite" (Windows only)
    "font_options": [],
    // Font options for theme text. Valid options are: "n
    // ...
}
```

One way to implement it: http://blach.io/2014/07/28/nsjsonserialization-category-to-read-json-with-comments/

**Comment by ad** [comment]
https://github.com/PureSwift/JSONC

**Comment by ad** [comment]
PR #39
