### ISSUE TITLE
Advanced Timeline/Scrubbing

### ISSUE THREAD

**Issue by samarthdave** [Toxblh/MTMR#351]
The issue #111 mentioned native timeline but was overshadowed by PiP mode. I really like this feature because websites that disable scrubbing on screen still work on the touchbar (ex. Facebook or Instagram).

When using Hulu, I can scrub through ads (Hulu doesn't like adblock enabled). I also use native scrubbing for YouTube shown below:

![image](https://user-images.githubusercontent.com/4997589/90963487-99c39c80-e47d-11ea-93d3-801d84191d1b.png)

Is there an easy way of going about this? I looked through the presets but couldn't find much from others :/
Note: Screenshot from new Edge browser (or anything Chromium)

Edit - screenshot from Hulu ad:
![image](https://user-images.githubusercontent.com/4997589/90963938-e3ae8180-e481-11ea-9d4c-044c6089169f.png)

**Comment by Toxblh** [comment]
Only what you can to do - it's move Edge or Hulu to blacklist. For disable MTMR while use the apps. We can't to integrate inside the pipeline of work touchbar for provide native widgets from apps
