### ISSUE TITLE
Is it possible to make appleScriptTitledButton clickable?

### ISSUE THREAD

**Issue by bobbykiselkov** [Toxblh/MTMR#352]
So basically, whatever I try, the appleScriptTitledButton would not work as a button. The script is called only when there is refreshInterval specified. I want to make a button with changeable icons on click. Is there any possible way to do that?

**Comment by cipi1965** [comment]
You can just add a "action" property, read the documentation. It's explained there.

**Comment by BorislavKiselkov** [comment]
Yes, indeed you are right but maybe I wasn't quite specific. Here is what I made:
  {
    "type": "appleScriptTitledButton",
    "align": "left",
    “action”: ”appleScript”,
    “actionAppleScript”: {
	   "inline": "set inputVolume to input volume of (get volume settings)\r\n\r\nif inputVolume = 0 then\r\n\ttell application \"System Events\" to set volume input volume 100\r\n\tset inputVolume to input volume of (get volume settings)\r\n\treturn {\" \", \"muted\"}\r\nelse\r\n\ttell application \"System Events\" to set volume input volume 0\r\n\tset inputVolume to input volume of (get volume settings)\r\n\treturn {\" \", \"unmuted\"}\r\nend if
     },
    "source": {
      "inline": "set inputVolume to input volume of (get volume settings)\r\n\r\nif inputVolume = 0 then\r\n\treturn {\" \", \"muted\"}\r\nelse\r\n\treturn {\" \", \"unmuted\"}\r\nend if"
    },
    "refreshInterval": 2,
    "image": {
      "base64": "iVBORw0KGgo…”
    },
    "alternativeImages": {
      "muted": {
        "base64": "iVBORw0KGgo…”
      },
      "unmuted": {
        "base64": "iVBORw0KGgo…”
      }
    }
  },

As you see on click the microphone is being muted or unmuted and then the "source" code is checked each 2 seconds in order to change the icon. Without the refreshInterval it does not work at all, nor without the "source" field itself. Is it possible to make it call the source only when clicked?

**Comment by r12habh** [comment]
@BorislavKiselkov Can you share your item.json file?

**Comment by bobbykiselkov** [comment]
Yes, of course, I posted it in my previous reply but it was unformatted

```
{
    "type": "appleScriptTitledButton",
    "align": "left",
    “action”: ”appleScript”,
    “actionAppleScript”: {
        "inline": "set inputVolume to input volume of (get volume settings)\r\n\r\nif inputVolume = 0 then\r\n\ttell application 
        "System Events" to set volume input volume 100\r\n\tset inputVolume to input volume of (get volume settings)\r\n\treturn 
        {" ", "muted"}\r\nelse\r\n\ttell application "System Events" to set volume input volume 0\r\n\tset inputVolume to input 
        volume of (get volume settings)\r\n\treturn {" ", "unmuted"}\r\nend if
    },
    "source": {
        "inline": "set inputVolume to input volume of (get volume settings)\r\n\r\nif inputVolume = 0 then\r\n\treturn {" ", 
        "muted"}\r\nelse\r\n\treturn {" ", "unmuted"}\r\nend if"
    },
    "refreshInterval": 2,
    "image": {
        "base64": "iVBORw0KGgo…”
    },
    "alternativeImages": {
        "muted": {
            "base64": "iVBORw0KGgo…”
        },
        "unmuted": {
            "base64": "iVBORw0KGgo…”
        }
    }
},
```

**Comment by Toxblh** [comment]
but, so, I tried it in Script Editor
```set inputVolume to input volume of (get volume settings)
if inputVolume = 0 then
	tell application "System Events" to set volume input volume 100
	set inputVolume to input volume of (get volume settings)
	return {" ", "muted"}
else
	tell application "System Events" to set volume input volume 0
	set inputVolume to input volume of (get volume settings)
	return {" ", "unmuted"}
end if```
And that doesn't work

Like example - that is work 
```
set curVolume to get volume settings
if output muted of curVolume is false then
	set volume with output muted
	return {" ", "muted"}
else
	set volume without output muted
	return {" ", "unmuted"}
end if
```


Also, with second script
It's your:
```
set inputVolume to input volume of (get volume settings)
if inputVolume = 0 then
	return {" ", "muted"}
else
	return {" ", "unmute"}
end if
```

But better to right like this:
```
set curVolume to get volume settings
if output muted of curVolume then
	return {" ", "muted"}
else
	return {" ", "unmute"}
end if
```

And in general fully worked example what you want:
```
{
        "type": "appleScriptTitledButton",
        "align": "left",
        "action": "appleScript",
        "actionAppleScript": {
            "inline": "set curVolume to get volume settings\r\nif output muted of curVolume is false then\r\nset volume with output muted\r\nreturn {\" \", \"muted\"}\r\nelse\r\nset volume without output muted\r\nreturn {\" \", \"unmuted\"}\r\nend if"
        },
        "source": {
            "inline": "set curVolume to get volume settings\r\nif output muted of curVolume then\r\nreturn {\"muted\", \"muted\"}\r\nelse\r\nreturn {\"unmute\", \"unmute\"}\r\nend if"
        },
        "refreshInterval": 2,
        "image": {
          "base64": "iVBORw0KGgo..."
        },
        "alternativeImages": {
            "muted": {
                "base64": "iVBORw0KGg..."
            },
            "unmute": {
                "base64": "iVBORw0KGg..."
            }
        }
    },```
