### ISSUE TITLE
image location for built-in button types

### ISSUE THREAD

**Issue by akulgoel96** [Toxblh/MTMR#360]
Hi,
I was looking for the image location for the built-in button types (specifically the `play` button) as I wanted to change the functionality of the button while keeping the button design similar to the previous and next buttons. Can someone point me towards the image location/base64 encoded value for the same?

**Comment by Toxblh** [comment]
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/system-icons/
https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/
