### ISSUE TITLE
timeButton plugin not showing date

### ISSUE THREAD

**Issue by goestav** [Toxblh/MTMR#364]
The date for the `timeButton` plugin seems to disappear (far right on the image) at times, but comes back after a minute or two.

<img width="1004" alt="touchbar timeButton bug" src="https://user-images.githubusercontent.com/27970303/98646695-a0024000-232b-11eb-9a16-83758b668c03.png">
<img width="1004" alt="touchbar timeButton bug 2" src="https://user-images.githubusercontent.com/27970303/98648273-f83a4180-232d-11eb-923f-0121bc3c4930.png">

<details><summary>My config</summary>

```json
[
    {
        "type": "dock",
        "align": "left",
        "width": 250
    },
    {
        "type": "battery",
        "align": "center",
        "refreshInterval": 60,
        "width": 60,
        "bordered": false
    },
    {
        "type": "weather",
        "align": "center",
        "icon_type": "images",
        "api_key": "ca93a0bb8cdb428552660d83249e4bc9",
        "bordered": false
    },
    {
        "type": "shellScriptTitledButton",
        "refreshInterval": 3600,
        "bordered": false,
        "source": { "filePath": "~/Library/Application Support/MTMR/custom/coronavirus/coronavirus.sh" },
        "align": "center",
        "image": { "filePath": "~/Library/Application Support/MTMR/custom/coronavirus/covid.png" }
    },
    {
        "type": "shellScriptTitledButton",
        "refreshInterval": 3,
        "bordered": false,
        "source": { "filePath": "~/Library/Application Support/MTMR/custom/bitcoin-euro/bitcoin.sh" },
        "align": "center",
        "image": { "filePath": "~/Library/Application Support/MTMR/custom/bitcoin-euro/bitcoin.png" }
    },
    {
        "type": "timeButton",
        "formatTemplate": "HH:mm | MMM dd",
        "align": "right",
        "width": 100,
        "bordered": false,
        "longAction": "shellScript",
        "longExecutablePath": "/usr/bin/pmset",
        "longShellArguments": ["sleepnow"]
    }
]
```

</details>

_Version 0.26.1 on macOS Catalina (10.15.7)_

**Comment by Th0m4** [comment]
That because the total width of your MTMR preset + the control strip width is to long for the touchbar
<img width="1004" alt="Touch Bar Shot 2020-11-13 at 11 15 19" src="https://user-images.githubusercontent.com/20077911/99061418-cd582380-25a1-11eb-9128-c290a1971205.png">

**Comment by goestav** [comment]
Looks like the width was the problem, thanks!
