### ISSUE TITLE
button for available free space left on disk

### ISSUE THREAD

**Issue by Th0m4** [Toxblh/MTMR#366]
Hi !
Do you know how to create a button like the "cpu usage" button but to indicate the available space left on my hard drive?

**Comment by Toxblh** [comment]
https://github.com/Toxblh/MTMR-presets
spaniakos shared similar already

**Comment by Th0m4** [comment]
No it's a button for memory not for storage !

**Comment by Toxblh** [comment]
```
  {
    "type": "shellScriptTitledButton",
    "refreshInterval": 30,
    "source": {
      "inline": "df -h / | tail -n 1 | awk '{ print $4, $5 }'"
    },
    "align": "left",
    "bordered": false
  },
```
