### ISSUE TITLE
[Big Sur] Brightness gesture does not work

### ISSUE THREAD

**Issue by cryomi** [Toxblh/MTMR#370]
No crashes, app restart does not solve it.

**Comment by Toxblh** [comment]
Please try to re-tick 
![image](https://user-images.githubusercontent.com/2198153/99725422-06fec200-2aad-11eb-8846-7437bd2b2249.png)
and check tick here 
![image](https://user-images.githubusercontent.com/2198153/99725454-1251ed80-2aad-11eb-98dd-288e28675de4.png)

**Comment by cryomi** [comment]
Works fine.
