### ISSUE TITLE
Cannot launch on macOS Big Sur

### ISSUE THREAD

**Issue by adammc1** [Toxblh/MTMR#376]
Hello, I have tried re-installing and everything but since the latest update and when running Big Sur I can't get MTMR to function at all. Any advice? Thanks.

**Comment by briansage** [comment]
MTMR only crashed for me when opening a particular group, so that helped me find `nightShift` was the culprit.

Comment out `nightShift` and restart to see whether that fixes it for you. If not, comment everything out and add your buttons back one at a time to see what works.

**Comment by adammc1** [comment]
Thanks, Brian. Commented out nightshift and everything worked fine thereafter! Shame because it was a useful little button to have, but glad to have my preset back again.

> MTMR only crashed for me when opening a particular group, so that helped me find `nightShift` was the culprit.
> 
> Comment out `nightShift` and restart to see whether that fixes it for you. If not, comment everything out and add your buttons back one at a time to see what works.
