### ISSUE TITLE
Previous/Next Buttons Not Working

### ISSUE THREAD

**Issue by OEverything** [Toxblh/MTMR#397]
I'm using a 16" MBP on Big Sur 11.3 Beta 3, and when I press the previous/next buttons, nothing happens.

{
    "type": "previous",
    "align": "right",
    "width": 40,
  },
{
    "type": "next",
    "align": "right",
    "width": 40,
  },

I also have a custom preset with this:

  // Music
  {
        "type": "appleScriptTitledButton",
        "source": {
          "inline":
            "if application \"Spotify\" is running then\rtell application \"Spotify\"\rif player state is playing then\rreturn \" \" & (get name of current track) & \" – \" & (get artist of current track)\relse\rreturn \" Resume – \" & (get name of current track)& \" – \" & (get artist of current track)\rend if\rend tell\rend if\rreturn \"\"\r"
        },
        "action": "appleScript",
        "actionAppleScript": {
          "inline":
            "if application \"Spotify\" is running then\rtell application \"Spotify\"\rif player state is playing then\rpause\relse\rplay\rend if\rend tell\rend if\r"
        },
        "refreshInterval": 1,
        "image": {
          "base64":
            "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAYUExURUdwTB3WXx3UXh3VXx7XYBkXFRpVLRyURmIaeAQAAAAEdFJOUwDDO3fSqUUkAAABbklEQVRIx61VbW6DMAztoAeYNA7ApB6gkzhAWS24wIAL0HABaK6/pHFNEhy8TXu/kPzkPD/8cTj8K7KPAqB+K5NhQPCUrABCXe7HOUYYZxgVRLiG8RfY4DUgFFtC7cffAfZTFBwBdhWEKfgEq4ocEjgj4ZQifO6/QG9kkETp1dDeVWfRKx3XYSW0LoqY5kCElXDrQkyeCCuh6WL0M4nIWQIyzqixdfKU1koFDKvyCA8NJMzU4xiD+b4kfHRpsIyKc6hBwjVptFHVY51EMAINNDFGJITKDNQcdpX74Hz0CQ3rY5qwMp4EIxrlafzrsYZ2Veb0DkRgfNCUok4Y1fqEijfyi2b8RE9beWqa48Y/uvCNMcH9btfUi+/CGLR1vhL6Zz9N/vBlaCU+7lwY/cmJ67Ryen/2tj23PLqJBodZH8vgj544vOL4pxfI5acrSFxi8hrkU9TSKr78ZpnL50A8KPJJEo+afBblwyqf5j/iGys5j6ScrST2AAAAAElFTkSuQmCC"
        }
    },
  { "type": "previous", "width": 40, "bordered": false, "align": "right" },
     { "type": "next", "width": 40, "bordered": false, "align": "right" },

**Comment by OEverything** [comment]
Update: It's an issue with the play/pause buttons in the system. The play/pause and skip/previous buttons on the touch bar (without the app) don't work at all.

**Comment by HigH-HawK** [comment]
Hey, please can you check the following on your machine?

🍏→ System Preferences → Security and Privacy → tab Privacy → Accessibility → MTMR

The checkbox next to it needs to be checked

**Comment by OEverything** [comment]
It is an issue with the normal touch bar, not MTMR specifically.
