### ISSUE TITLE
Apple M1 Builds

### ISSUE THREAD

**Issue by thypon** [Toxblh/MTMR#403]
As the title suggests.
Would it be possible to have native Apple M1 builds instead of the rosetta emulated ones?

**Comment by xcity** [comment]
You can build by yourself, as I did in my M1, it's pretty street forward process. If you don't know, I can just give you to try it out.

**Comment by fabix683** [comment]
can you share the compiled version for m1?
TNK

**Comment by maxminoS** [comment]
@xcity I have tried compiling by trying to run the `test.sh` and archiving/building in Xcode, but for some reason these aren't working.

Here is the error message I am receiving:
```objc[53122]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x20c558188) and ?? (0x11614c2b8). One of the two will be used. Which one is undefined.
objc[53122]: Class AMSupportURLSession is implemented in both ?? (0x20c5581d8) and ?? (0x11614c308). One of the two will be used. Which one is undefined.

❌  error: No signing certificate "Developer ID Application" found: No "Developer ID Application" signing certificate matching team ID "D6D8BR2QNB" with a private key was found. (in target 'MTMR' from project 'MTMR')


** ARCHIVE FAILED **```

Not sure what exactly I'm doing something wrong.

**Comment by lucasvel** [comment]
any chance on getting a compiled version? Not even in the noob category here on ios development here, but would really like to enjoy this app 😃
