### ISSUE TITLE
Add siri Button

### ISSUE THREAD

**Issue by Rahulsharma0810** [Toxblh/MTMR#419]
I am not able to find any example or preset where I can set SIRI for voice commands.

Let me know if the option is there.

**Comment by mdreece** [comment]
Not sure if you're still looking for an option, but this has been the best I could do so far

    "type": "staticButton",
    "align":"_Wherever you'd like_",
    "image":{
      "base64":"_PNGtoBASE64_"
    },
          "action": "shellScript",
          "executablePath": "/bin/bash",
          "shellArguments": [
            "-c", "open -a Siri"
          ],
          "title": "",

**Comment by Rahulsharma0810** [comment]
I did this if someone want to use it, or give me bas64 of the SIRI look-alike icon.

```
  {
    "type": "staticButton",
    "align": "right",
    "title": "⧂",
    "width": 60,
    "background": "#45b1e5",
    "action": "shellScript",
    "executablePath": "/bin/bash",
    "shellArguments": ["-c", "open -a Siri"]
  }
```

**Comment by mdreece** [comment]
SIRI Base64:

"iVBORw0KGgoAAAANSUhEUgAAADYAAAAjCAYAAADfXvn1AAAACXBIWXMAAAABAAAAAQBPJcTWAAAAJHpUWHRDcmVhdG9yAAAImXNMyU9KVXBMK0ktUnBNS0tNLikGAEF6Bs5qehXFAAALdklEQVRYhcWZe4xd11WHv7X3ed3XPD0zdhy/x4njNIlDmrYpKYE2gUAqEUoVRCilgKBBUJG0vBSKgBRR8WiUBLUFJKQCRSVqi0gaKihVKjW0KYKSyE0cJ/aMPX6OPc74zsyde+957LX4447Dv2Myabe0dKStrX1+317rrLP32sIb0GZmZtKJiYlb0yS5xXm/X0S2ikhTQA3aiJxA7aBhzywvLz83NjZmG61BNnKyCwsLBxqN1oei2P+kd344aGB29hQnjp9lqd0BYHiowbadW9iz50q8jzA4adhnVe2TSRyd3igtGwI2Pz+/o9Ua+kSSpu8p+oV86Z+f5okvPM03vv4cnZU+huAwzDlEHDih0axxy63X8+67b+Puu2+jXq/navqpoOEPszRd+p6Czc3NMTQ09IFarf4XIWjzbz79RT718Oe4cKENJpgMXiECiCBuAIV34NxgEicMjzT54Ad/gvvuew9ZLT0dNLw/S9Onvydgx44dc6OjY5+o1eq//sLzR+T+X/o4R14+iWGvzWwDInCCOAYwl6DcoN/EAYYp7Ng+yWOPPsCb37w/hFB9eG7u+GP79u377oHNHT/O0PDoX9VqtV9+8vNf48Ffe4S8KAFBhQGcyGB2EfCCOTAniPeYv+Q9t7YMAmaYGV6EP3roF7n3p+8kaHiwUc8+/l0De3Xx4kdrWf1j//TZf+MPPvyXmNlrUMAAQgYgJgIO8IJGgnmHXApHEcwNvGpmoGBBQZWP/s77+IUP3GUaqp9vtpp/+4aDnTt3/rZGo/H0N7/2nHvgZ/8EDQOSSwDq1r4tZ6hzAzhnEAkhWgs/7zAvg5AUwRAwBj8DNUwVUeXRP/tV7rzj5n5ZFm8dHR05+IaBzczMZONjEwcvLi7tfd8dv8HyYhdnEYgf5D3nMAfqBzD6GoShkVBFAtEAfhCebk2BYOZADTHDgmJBqWcxT/zD77P1ivFvnz8//5bp6Wldr1Z3OWCt1vCviLi9jz30GbrLXWIfkUSezMdkUbpmGVmUkkYpSZqRpDXiNCNKU6IsxaUJPhuYqyW4LIFagqvHuFqCZIM+V4vpm/HQw/8Iyk2jo5t+7nK0rhvs6NGZ2LvoIy9/Z4b//Or/kEYxqfckPiLxEamPSX1KEiWkUUIcJ6Tx4BknKXGaEKUJPktfA5AsRmoDCMliXG1gUhv0k8V84+ARnn3uZUTkwZcOHV633mi9A+v15l0gW//lc/9OPUmx4EAFsQgxj0gMEmFeqLzhIyNEgo8SNDaqxLBYkAg0huAZhOPaxyCAKYgyCMkQMFWolL978uvcfN2e6dHRsduBr2womHfuvd1Ol0PfeolWVsMqwSq/lgI9jgiViODBeaWKwEdCSBIsFVwiWOaQWAixgFPEKQEFBqle1jKjBBskk0qwIHzz0AwLF5cZadV/akPBZmZmxYx3Hv72K9RdjKaCRB4qh2oEKhgRJo5SBOcqXASaeKxWR7OEqO6RekKReUIClQuUFGjIsVBgocJCQIKChkFEeEEVrFKeef4w7771xjuOHZ9j184dGwNmylZTtpw9coqRRg1XDaCoIrTyqDqCeQqgAHxkVKlH6ynaGCW0hgjDNdxYk2isQVVzFL6AagXyJYpuG+0sQ6+L9ftQGlIpEsAqQUV4bvYEd739xm2hDJuB+Q0Bi6J4Wk0pLiyxtdXEa4yrYggJoYoogqdQoReM3DkKH1HWaxTDQ4SprXDNNmxLi6KRkjtHiAyJBYsDXVllMT9Pe+EY1elT6IUL2Moq0sshL6FyWGEcnT+PqhFFyd4NAzNjIgRlgsDkpklEh8EamNYQzVBz9NVY0YiuS1lN63RHW+QHRli9oslS39HNjfyC0iOHlpCMRqSZY1OjxUTU4uLuKznSnWPx8CHs+GnkQhvf6SOdAhNlvrNCUAWYWpcz1jMIk8zUqBavpurU8HGGxA0aaYuxJCVLGyStBBkX8k3CuWGYmxTmloXFNuS54psVtU0VaUPpOSOXnF4Q6DpcBD4V9jV38eoPTHLmukN0Dh6hc/QccqGDtJWVqsJUMSPdMDBFc0zoh4RImlzpM/ZKn5Z2yKsUTSao1TYTT4PdBFdWUCxA2yvVVshqRjs3lnPorijdUNFTJUcpCSiK+IBPhayRMD45jb8pprWpzursWTrHXsUtKaqgpsWGgZnagooxUc9407klxjvz9HzgvI/pJsOYRNRGjXSLICeFujPeNQpXbhae7sBKWyl6Ql5AXjiq4DGT12wAZ2inZHUpJ2t7ahNbaE8YbjXQRJhaMdQMMz2/cWAWZsyEndlF0oUl2pmnlySsJnV6yRjhhmHOTjukowyNQ+KEZBkmF+HHvPFk6ljNhW4OXpWR1LN1kzDUdOCMTl850y55+XxOr+jT7RdE/Zzm2BSvbs/o6Sw7MkU1oFod3TCwKPYny0IXentbE0tfXsG7IYpkFL1iC8UPT9GZitARo+8c5zrgCkgDNA1Gg3C3wEhNeHkC9mzzjE14qrXjmgcig0gyQtHk2Zk+T720TLtfENrKUDRFcfUUBxYWUNWzSeLXVRdZ9+7+8EvHHg8r1T36M3MMbd1DdfsEvR/M6IwKi+ZYXIbVHEI52DkkJmQBWsEY98a110G53fECRluEAHiDWAyP4NbOpg6oSuWJV3o8tVyyy0UcmO9z7+4VRiL5+337d71/Xc5YL5iIfVHq/p7q3p34WzbTuDZieMjRK6DeVQjQXhXKciCyUuiX0Bo19r5FSBNhuIC3RcKsMy6KEAEJggNUoDSoBDRyfOiaGr/bTpEvl5w8tsLQtGDY59etd70DZ2ePp/1uOFHmOjm5eZzhkSZxEiFeqARKjDzAzCnjO7PQ7wnX7TF2TQuUQlbBiIc4G7w1B/oYYU2CAYUNBI2YERsUecXKcpezp88Tp/5Emsme6b27q/XoXfcxYPfunbmIPeoiuLBwkbIMhKCoGsEMRRAnXLPD8Y79xr7tyjVXDU7HoqwVc/5vKVNgGGEEGDZjFNgsxhSQAFWllGVgYWERHwtgf7peKLiMUATI6vEjq8v5fVUoty0uXGTT1BiJRHjxVME4uWC8eFw4u+iRAGfOK2+7GRqZICWI2mDD7GDZjB6CiOHWKgM9IJjRrJRGGWgvLlGWBZF3h5I0+uvL0XrZNY/DLx29q9+vvrS8YrLiJ3FJg3bhOd/xlAqqggCRQhKMYTXeegB27hAiFbrOeEVgZVAlIDYhEsCgUiMEpSwC/XaX1tmzZN5XUSzveNP1V33rDQUDOPTCkT/v98NH5peNczJFnwb90hNUAEcE1ICWwkiA8WDsmDLCAZhLHW0xqrWkEdnAnClSGZSB/3pxCX9mnndui/GRe+D6G69+5HI1XlYoXmpDI7Xf1sXujs3N6r3aPcsJmyRKW1B4HFBHGHYwIcIkMBbBMxE8898w1gxs3wZjo46AoKx5qRt4cabgK8+e47bGEj9+bQ3x8nBzOLlsKHgdleCTJ0/ESxf7n+n3q3vbuTJbtIiSceIQ08Qx4YUtTqjVjac8HFpWXl0JrPSMXmmAUc9Ag7G0UjJ/oUe8ssD9Nyg3bE3NR+6Ph4az39uzZ9f/6ybmddXuT585LUuLq7/V7VYfC5XF5/qCuGG2pMNsSSLmE+FfS2G+U7HUDXTzil6h9HMlLwN5oXR7BfnSRX50c8E9+xtkCe0o9vfd+H3XPP56tG3IbcuRV2YOrHbKTxZ59Xa1wV/2uGT8R6/BSpnRL6GoKvplRZ6XrPZyep1VtscFN43BD+3MqMXOvJfHk9T/5vU37Dv1ejVt2P3YmTOnWF7q39nrlfdXZbhdg/lgcK5nLPShWyqqSuqU8cyxrRXhneCcrDonX4hj/8gNN+57fqP0bOjF36V27NjxqU6n/yNlod+vQfcbXGFGCyyALAnMiXDQefdMs5l99aqrd3c3WsP/AqaKiB2zcaCQAAAAAElFTkSuQmCC"
