### ISSUE TITLE
whitelist apps to let them use own touch bar

### ISSUE THREAD

**Issue by akme** [Toxblh/MTMR#42]
Some apps has nice and useful touch bar, so it'll be good to let add them to some whitelist, so they won't be hijacked by MTMR. BTT has this thing like exclude specific apps.

**Comment by nvartolomei** [comment]
Next level would be to have the possibility of delegating a specific part of touch bar to be hijacked by whitelisted apps. 

Ie. I'd want to have esc button on the left always visible and brightness, volume, battery, clock on the right, while middle part can be delegated to apps.

You can view this as how Touch Bar behaves by default, but with ability to customize the right group.

**Comment by akme** [comment]
Looks like you need to get control strip back and customize it ;)

**Comment by nvartolomei** [comment]
@akme unfortunately native customizer does not offer such flexibility.

**Comment by akme** [comment]
@nvartolomei it's pretty hard to get native customizer work with hijacked stuff, i'm saying that it's easier to put needed things in control strip, delegate touchbar to app and hijack esc ;)

**Comment by Toxblh** [comment]
I love the idea to provide the central part for white apps. Need to investigate the moments maybe it is posible.
The simple way - to exit from fullscreen mode MTMR for whitelist apps.

**Comment by ad** [comment]
PR #74
