### ISSUE TITLE
Two currency-elements: second won't update

### ISSUE THREAD

**Issue by rvinke** [Toxblh/MTMR#43]
I have two currency-elements:

`{ "type": "currency", "refreshInterval": 60, "from": "ETH", "to": "EUR" }`
`{ "type": "currency", "refreshInterval": 60, "from": "LTC", "to": "EUR" }`

The second one won't update. Only when I do a "reload preset" the second one gets updated.

**Comment by ad** [comment]
PR #45

**Comment by rvinke** [comment]
Nice!

**Comment by rvinke** [comment]
I've tested 0.13.1, and the problem is solved. Thx!
