### ISSUE TITLE
copy and paste button

### ISSUE THREAD

**Issue by xunshichentuo** [Toxblh/MTMR#457]
May I know how to add custom buttons, such as copy and paste

**Comment by juanfernandocalderon** [comment]
{ // Copy
            "type": "staticButton",
            "title": "Copy",
            "action": "appleScript",
            "actionAppleScript": {
            "inline": "tell application \"System Events\" to key code 8 using {command down}"},
            "width": 60,
            "align": "left",
            "name": "Copy"
        },

        { // Paste
            "type": "staticButton",
            "title": "Paste",
            "action": "appleScript",
            "actionAppleScript": {"inline": "tell application \"System Events\" to key code 9 using {command down}"},
            "width": 60,
            "align": "left"
        }
