### ISSUE TITLE
Button for lock screen

### ISSUE THREAD

**Issue by bowlingkopp** [Toxblh/MTMR#50]
Hey,

first of all, thank you for this tool, great idea buddy! :)
I would like to change the behavior of your sleep button to just lock the screen. Could you implement this? Something like mode={sleep|lock} maybe :)

**Comment by ReDetection** [comment]
Hi @bowlingkopp 

Do you want your computer to 
a) stay active, but display shut off
b) or to lock screen while display stay on?

I'm asking because for the option A we already have `displaySleep`, and I don't really know any good solution for the B. Do you aware of good terminal command maybe or a stable API to do that?

**Comment by Toxblh** [comment]
Hi @bowlingkopp and @ReDetection 
Now our sleep (coffee) button do deep sleep.
`"type":"sleep"`
`/usr/bin/pmset sleepnow`

but we also have the additional type, only for display sleep
`"type":"displaySleep"`
`/usr/bin/pmset displaysleepnow`

**Comment by Toxblh** [comment]
Second like a lock screen without a screensaver

**Comment by bowlingkopp** [comment]
Thank you, but I meant just a Lock screen. The thing is, I'm using a Lenovo Thunderbolt Dock with two external monitors. When I put the macbook to sleep and wake it up again, the second monitors stays asleep in the most cases. So I would like to have the function to just lock the screen. To keep my Macbook from going to sleep I'm using Amphetamine.

**Comment by ReDetection** [comment]
Ah, then maybe screensaver will suffice? Please try this one (I have no external monitor so can't check against it, but macbook screen stays on):
```json
{
"type": "staticButton", 
"title": "test", 
"action": "shellScript",
"executablePath": "/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine",
},
```

**Comment by slyoldfox** [comment]
People looking for  other alternatives:

Display the "Switch User" screen, this is command
`/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/
  Resources/CGSession -suspend`

Display the "Lock screen" (current user with a password login prompt), this is a command but I suppose you can also use the applescript inside the quotes directly
osascript -e 'tell application "System Events" to keystroke "q" using {control down, command down}'

**Comment by fgilli** [comment]
@slyoldfox Hi, how can i include this code in the .json file?

**Comment by Skinner927** [comment]
I just wanted to add my solution here in case anyone lands here as I did.
I wanted to be able to lock the screen & pause any music that was playing. When a mac goes to sleep it automatically mutes anything playing, but if your "Require password after sleep or screen saver" setting is not instant there would be no lock screen with just a sleep.

Here's my solution to lock the computer & put it to sleep regardless of what your "Require password after sleep or screen saver" setting is.

```
    "longAction": "shellScript",
    "longExecutablePath": "/bin/bash",
    "longShellArguments": ["-c", "osascript -e 'tell application \"System Events\" to keystroke \"q\" using {control down, command down}' && /usr/bin/pmset sleepnow"]
```
