### ISSUE TITLE
Beachballing on MacOS 10.13.3

### ISSUE THREAD

**Issue by joshuaswilcox** [Toxblh/MTMR#52]
I tried to install via Brew, but everytime I open it, it just beachballs and and the touchbar is unresponsive

**Comment by Toxblh** [comment]
only for an experiment, can you open iTunes before launch MTMR?

**Comment by joshuaswilcox** [comment]
That didnt seem to help, also I tried the regular download version as well and same thing happened

**Comment by Toxblh** [comment]
Maybe - need to delete not using widgets in the settings. On the last version sometimes it happens when was VOX widget but haven't the application
