### ISSUE TITLE
iTunes title scrolling

### ISSUE THREAD

**Issue by bowlingkopp** [Toxblh/MTMR#61]
Hi,

it would be great if the iTunes plugin/script would scroll from right to left if the artist and title is too long to be displayed as a whole on the Touch Bar. Is it clear what I'm trying to say?

**Comment by Toxblh** [comment]
Yes, it's clear... Need to find a solution how to do it better

**Comment by bowlingkopp** [comment]
Ok, thanks for your effort buddy! Btw. are you taking donations?

**Comment by Toxblh** [comment]
https://www.patreon.com/toxblh a bit)

**Comment by Toxblh** [comment]
pr #64
