### ISSUE TITLE
Add ability to do not hide standart control strip (controls at right), like in BTT

### ISSUE THREAD

**Issue by ad** [Toxblh/MTMR#68]

**Comment by Archieru** [comment]
Expected: an option to have the default 4 buttons always available
![image](https://user-images.githubusercontent.com/5917147/39878820-f9386daa-5481-11e8-8782-aff91f070cef.png)
Why: I like mac default volume and brightness control more.

**Comment by ad** [comment]
PR #73

**Comment by PierreBrisorgueil** [comment]
@ad thx for this 
I came across it by chance on code search, it may be missing the Readme documentation update in the PR ?
