### ISSUE TITLE
Add ability to change the MTMR button in control strip

### ISSUE THREAD

**Issue by Archieru** [Toxblh/MTMR#71]
I expect it to be black+white:
![image](https://user-images.githubusercontent.com/5917147/39880685-26ec3312-5487-11e8-8297-5fec9aa08276.png)
but I see
![image](https://user-images.githubusercontent.com/5917147/39880722-3e0f5dda-5487-11e8-91f4-62d8ea83a639.png)
that leads to not so solid style
![image](https://user-images.githubusercontent.com/5917147/39880813-848ce246-5487-11e8-8786-0e9dde9fae76.png)

**Comment by PierreBrisorgueil** [comment]
nice feat to personalise :) 👍 
if this feat disturbs, to keep an image of the project, would it be possible to remove the border? the button overflows a bit compared to others :)

**Comment by Archieru** [comment]
I expect it OR
to be customizable
![image](https://user-images.githubusercontent.com/5917147/39954746-ce3b97e8-55cc-11e8-984c-be9f176cd54e.png)
OR just change the icon to white

**Comment by ayman** [comment]
Also, on the point here, the icon has zero padding...it shouldn't run up to the edge of the button frame rather have a few pixels of padding.

**Comment by PierreBrisorgueil** [comment]
@Toxblh thx for change, could be closed for me

**Comment by Archieru** [comment]
Looks much better. Thank you
