### ISSUE TITLE
Is it possible to add a specific fn key to the control strip?

### ISSUE THREAD

**Issue by tonyxiao** [Toxblh/MTMR#78]

**Comment by Toxblh** [comment]
What do you mean? If it possible, can you provide an example?

**Comment by tonyxiao** [comment]
I would like to add F5 to the control strip because it's bind to a global keyboard shortcut that I would always like to have access to (push to talk). I don't care as much about the other function keys so I don't want to have all 12 fn keys on display on touch bar.

**Comment by Toxblh** [comment]
So. Yes you can do it, but for full implementation in control strip, and have regular touchbar you need create another project like this https://github.com/nihalsharma/Clock-Bar

But you can add the Fn keys to mtmr
codes: https://eastmanreference.com/complete-list-of-applescript-key-codes
button:
```js
{
    "type": "staticButton",
    "align": "left",
    "title": "F5",
    "action": "keyPress",
    "keycode": 96,
    "width": 64
  },
```

**Comment by tonyxiao** [comment]
That's awesome. Can you clarify what you mean by `full implementation in control strip, and have regular touchbar`?

**Comment by Toxblh** [comment]
@tonyxiao I about if you want to set the button in control strip where clock in the image:
![image](https://user-images.githubusercontent.com/2198153/40169442-eaa30836-59bd-11e8-9540-80b22e099b21.png)
