### ISSUE TITLE
Gestures for actions

### ISSUE THREAD

**Issue by akme** [Toxblh/MTMR#81]
One guy showed on [reddit](https://www.reddit.com/r/macapps/comments/8iww7b/you_cant_live_without_bettertouchtools_if_you/) how he's using gestures in BTT.

> I'm using two finger swipe to change the volume and three finger swipe to change brightness. You don't need to press a button and grab a slider, it works no matter where you press on the touchbar.

> In the most recent update (2.500), go to the touchbar section and click on the "+Widget/Gesture".
> I have it set up with left swipe to "Turn volume down - small step" and right swipe set to "Turn volume up - small step".

Would be nice to have something like this =)

**Comment by ad** [comment]
PR #84
