### ISSUE TITLE
"no script" on valide appleScript

### ISSUE THREAD

**Issue by PierreBrisorgueil** [Toxblh/MTMR#87]
Hello, 

just find something strange today : 

```
 "source": {
    "filePath": "/Users/xxxx/Documents/appleScript/vox.applescript",
}
```

```
if application "VOX" is running then
	tell application "VOX"
		if player state is 1 then
			set myArtist to (get artist)
			set myTrack to (get track)
			return myArtist & " – " & myTrack
		else
			return ""
		end if
	end tell
end if
```

result is ko -> no script

with inline : 

```
    "type": "appleScriptTitledButton",
    "source": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rset myArtist to (get artist)\rset myTrack to (get track)\rreturn myArtist & \" – \" & myTrack\relse\rreturn \"\"\rend if\rend tell\rend if"
    },
```

result is ok

**Comment by Toxblh** [comment]
Yes, now work only inline scripts.

**Comment by ReDetection** [comment]
what? I have them working, two of my apple script widgets are running like that right now. 
@PierreBrisorgueil can you please check if your file is really there and full path is correct? It's a common case to have case-sensitive filesystem and a small mistake in the path
```
ls -la /Users/xxxx/Documents/appleScript/vox.applescript
```

**Comment by Toxblh** [comment]
Sorry,  Is it my mistake. I see it as all in config. Yes, files should be work correct

**Comment by PierreBrisorgueil** [comment]
Not ok for me, script works fine for my buttons "action": "**appleScript**"

But for **appleScriptTitledButton**, when the script must return the string value : 

## With my Apple Script : KO 
(but the apple script seems to work fine in apple editor)

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "filePath": "/Users/xxxx/Documents/Dev/appleScript/vox.applescript",
     },
    "action": "appleScript",
    "actionAppleScript": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rnext\rend if\rend tell\rend if\r"
    },
    "refreshInterval": 1,
    "align": "left"
  },
```
```
if application "VOX" is running then
	tell application "VOX"
		if player state is 1 then
			if length of (get artist) is less than 15 then
				set myArtist to (get artist)
			else
				set myArtist to text 1 thru 15 of (get artist)
				set myArtist to (myArtist & " ..")
			end if
			if length of (get track) is less than 10 then
				set myTrack to (get track)
			else
				set myTrack to text 1 thru 10 of (get track)
				set myTrack to (myTrack & " ..")
			end if
			return myArtist & " – " & myTrack
		else
			return ""
		end if
	end tell
end if 

```

return = no script

## With a simple Apple Script : OK 

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "filePath": "/Users/xxxx/Documents/Dev/appleScript/vox.applescript",
     },
    "action": "appleScript",
    "actionAppleScript": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rnext\rend if\rend tell\rend if\r"
    },
    "refreshInterval": 1,
    "align": "left"
  },
```
```
return "test"
```

return = test


## With a my Apple Script inline : OK 

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rif length of (get artist) is less than 15 then\rset myArtist to (get artist)\relse\rset myArtist to text 1 thru 15 of (get artist)\rset myArtist to (myArtist & \" ..\")\rend if\rif length of (get track) is less than 10 then\rset myTrack to (get track)\relse\rset myTrack to text 1 thru 10 of (get track)\rset myTrack to (myTrack & \" ..\")\rend if\rreturn myArtist & \" – \" & myTrack\relse\rreturn \"\"\rend if\rend tell\rend if"
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rnext\rend if\rend tell\rend if\r"
    },
    "refreshInterval": 1,
    "align": "left"
  },
```

the only one idea I have for the moment is the return : 

- when i'm on inline, the text seems to be ok : 
"Dennis Kruissen .. – Don't Thi .."

- when i use my script : 
<img width="725" alt="screen shot 2018-05-31 at 13 52 15" src="https://user-images.githubusercontent.com/6069599/40780905-51bf8c7a-64da-11e8-8491-40436619af4c.png">

we have this "Dennis Kruissen .. – **\"**Don't Thi .." 

I was wondering if the problem is not this \"  

- but when I try to do this in apple script 
<img width="570" alt="screen shot 2018-05-31 at 13 57 37" src="https://user-images.githubusercontent.com/6069599/40781004-9e5219fe-64da-11e8-9655-9fdc219ed1ff.png">

it works, and when I call this from mt, this loops the next script called in the configuration. 
that's seem to be normal .. but maybe we can escape the string return by apple script by default to protect that  ? 

and that doesn't explain my problem for the moment "no script" 

maybe I'm missing something

**Comment by ReDetection** [comment]
"no script" error occurs only when failed to load script from disk, this happens even before trying to compile script, so I'm pretty sure script itself is fine and error is somewhere else, my guess is wrong path. Please double check it. In latest message you have `Dev` path component which was missing before. 
If you sure that file is there and `ls` command shows no error, then we have to check some basics first: which version of MTMR you are running? Did you download it from releases section as dmg image, zip archive, or you checked out the source code and built by yourself? Do you have spaces in your home folder or any other symbol that you have to escape in bash? (In MTMR config only regular JSON escaping should be applied, not bash escaping needed)

**Comment by PierreBrisorgueil** [comment]
it's not the path : 

## script simple 

```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "filePath": "/Users/pierrebrisorgueil/Documents/Dev/appleScript/test.applescript",
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rnext\rend if\rend tell\rend if\r"
    },
    "refreshInterval": 1,
    "align": "left"
  },
```

<img width="754" alt="screen shot 2018-05-31 at 16 33 51" src="https://user-images.githubusercontent.com/6069599/40788487-7dfbd1f2-64f0-11e8-9ce3-ae5b47de1bb4.png">

Text button is : "test"

## my script 


```
  {
    "type": "appleScriptTitledButton",
    "source": {
      "filePath": "/Users/pierrebrisorgueil/Documents/Dev/appleScript/vox.applescript",
    },
    "action": "appleScript",
    "actionAppleScript": {
      "inline":
        "if application \"VOX\" is running then\rtell application \"VOX\"\rif player state is 1 then\rnext\rend if\rend tell\rend if\r"
    },
    "refreshInterval": 1,
    "align": "left"
  },
```
<img width="951" alt="screen shot 2018-05-31 at 16 37 28" src="https://user-images.githubusercontent.com/6069599/40788726-00a5ef0c-64f1-11e8-97ff-b58c3f74dad0.png">

Text button is : "no script"

Path seems to be good. 

Does anyone can test my script quickly ? downloaded from releases section as dmg image 0.16, no escape, no space.

i call the .applescript because the .scpt does not seem to work with mt for me. 
Done with Apple script editor, export in text format.

my scpt save : 
<img width="700" alt="screen shot 2018-05-31 at 16 43 41" src="https://user-images.githubusercontent.com/6069599/40789261-4b197bc0-64f2-11e8-8081-a98123748379.png">

my applescript save : 
<img width="698" alt="screen shot 2018-05-31 at 16 43 54" src="https://user-images.githubusercontent.com/6069599/40789263-4db5ca3c-64f2-11e8-9a47-ab5d0ff0eebe.png">

**Comment by ReDetection** [comment]
I tried yours and I got empty button as I don't have VOX player. I didn't got any "no script". I understand your struggle, but I'm still convinced there is some problem with file loading. You told me you got test script working. Can you please copy-paste vox script content to the test script and restart MTMR please? If this doesn't help then I have no ideas what's going on

**Comment by PierreBrisorgueil** [comment]
Already tried and same result :/

hum, can you try this for iTunes ? 

```
if application "iTunes" is running then
	tell application "iTunes"
		if player state is playing then
			if length of (get artist of current track) is less than 15 then
				set myArtist to (get artist of current track)
			else
				set myArtist to text 1 thru 15 of (get artist of current track)
				set myArtist to (myArtist & " ..")
			end if
			if length of (get name of current track) is less than 10 then
				set myTrack to (get name of current track)
			else
				set myTrack to text 1 thru 10 of (get name of current track)
				set myTrack to (myTrack & " ..")
			end if
			return myArtist & " – " & myTrack
		else
			return ""
		end if
	end tell
end if
```

I have the same result. 

if this work on iTunes for you, do you use Script Editor ? or juste classic editor to create the script ? how do you save it ? .applescript or .scpt ? 

if we find nothing with this last test I will not bother you anymore and I'll do a build at home to understand :) 

(but I think we shouldn't forget about the looping script I mentioned above, in case of a string with one " return)

**Comment by ReDetection** [comment]
I use Sublime text editor, I save as `.scpt`, but as long as this is just a text file, file extension doesn't matter. I get normal output from iTunes playing Billy Talent.
<img width="1085" alt="touch bar shot 2018-06-01 at 09 05 59" src="https://user-images.githubusercontent.com/458005/40817155-070dda50-657b-11e8-8779-e624adebcca4.png">
If you try to build from sources, I'm definitely interested in a result.

**Comment by ad** [comment]
Please check the line "return myArtist & " – " & myTrack" in result file (open it in alternative text editor). Script Editor replaced "dash" with symbol in alternative encoding.

**Comment by ReDetection** [comment]
Oh, yeah. It seems to be an encoding issue. I expected utf8, while script editor emits ISO-8859 encoding

**Comment by PierreBrisorgueil** [comment]
@ad 👍 perfect :) 

in sublime : 
`return myArtist & " Ð " & myTrack`

Testing the apple script for the first time I did not expect it. 

@ReDetection thx for fix :) 

if someone have time I think we can test this again  : 

<img width="698" alt="" src="https://user-images.githubusercontent.com/6069599/40781004-9e5219fe-64da-11e8-9655-9fdc219ed1ff.png">

Check if the infinite loop is still relevant, it broke the JSON file and triggered the next script in a loop.  This can be dangerous depending on the contents of the following script.
