### ISSUE TITLE
feat: multiple kind of actions

### ISSUE THREAD

**Issue by PierreBrisorgueil** [Toxblh/MTMR#91]
hello,  me again!  just a quick idea. Since i saw this integration : 

> music (tap for pause, longTap for next)

i thougt it was about a new feat for all buttons, quick example : 

```
  {
  	"type": "staticButton",
  	"title": "🛩 ",
        "actions" : [ {
            "kind": "tap",
            "type": "appleScript",
            "actionAppleScript": {
    	         "filePath": "script1.applescript",
             }
         },{
            "kind": "longTap",
            "type": "appleScript",
            "actionAppleScript": {
    	         "filePath": "script2.applescript",
             }
        }],
 	 "width": 34,
 	 "align": "right"
  },
```

I thought about fours actions : 

- tap
- longTap
- doubleTap
- tripleTap

example with vox or itunes (this reduces the number of buttons and saves space)

- tap -> next
- longTap -> pause
- doubleTap -> previous 
- tripleTap -> quit

example with reminders

- tap -> check last task 
- longTap -> switch from list 
- doubleTap -> open reminders in front  
- tripleTap -> quit

example with a custom timer in apple script (inspired from [touch bar timer](https://www.producthunt.com/posts/touch-bar-timer)) 

- tap -> start/pause
- longTap -> reset 

Actually I'm talking about script by action, but I'm just starting to test AppleScript, maybe we can give the var "kind" two the script, in order to have one script for all actions. 

I'm juste sharing the idea, as soon as I have a little time I would not hesitate to PR if I can :) 

Really cool project, it's the  first time I feel that i can do something with my Touch Bar 👍

**Comment by mandre42** [comment]
👍

**Comment by Toxblh** [comment]
Oh! I didn't update readme!
already have longPress

longAction

```json
{
  	"type": "staticButton",
  	"title": "🛩 ",
        "actions" : [ {
            "kind": "tap",
            "type": "appleScript",
            "actionAppleScript": {
    	         "filePath": "script1.applescript",
             }
         },{
            "kind": "longTap",
            "type": "appleScript",
            "actionAppleScript": {
    	         "filePath": "script2.applescript",
             }
        }],
 	 "width": 34,
 	 "align": "right"
  },
```

**Comment by Toxblh** [comment]
I try do it on the weekend. Yes need additional actions :)

**Comment by PierreBrisorgueil** [comment]
@Toxblh thx for long :) 

Always for a rework of json template with an array of actions like my example, it makes more sense to me than a list of key in an object. long / short / ... are different things from the types of action. 

```
  {
  	"type": "staticButton",
  	"title": "🛩 ",
        "actions" : [ {
            "kind": "tap",
            "type": "appleScript",
            "action": {
    	         "filePath": "script1.applescript",
             }
         },{
            "kind": "longTap",
            "type": "appleScript",
            "action": {
    	         "filePath": "script2.applescript",
             }
        }],
 	 "width": 34,
 	 "align": "right"
  },
```

and home double tap :)

**Comment by cipi1965** [comment]
Hi, i have implemented a new `actions` parameter and double tap.
See PR #349 
I would like to implement triple tap. Maybe in the next days 😃

**Comment by cipi1965** [comment]
@Toxblh i think we can close this?
