### ISSUE TITLE
No way to exit from group

### ISSUE THREAD

**Issue by trntv** [Toxblh/MTMR#97]
Hi everybody, it is strange, but i've found no way to exit from opened group (return to mtmr bar). There is no "type" for it. What i'm missing?

**Comment by ReDetection** [comment]
Hi @trntv. Please try this
```
      {
            "type": "close",
            "align": "right"
      },
```

**Comment by trntv** [comment]
Thats worked! Thank you. btw, it definitely should be in readme ;-)
