### ISSUE TITLE
Buttons sometimes do not trigger action

### ISSUE THREAD

**Issue by Kevin-Prichard** [Toxblh/MTMR#99]
MTMR is great for me in all but one way: touching the buttons sometimes produces no result.

It can happen in any app, and I've tested across many.  I believe it has to do with touch duration.  If I hit a button really fast, the button brightens, but the haptic and the action do not fire.

Is there a threshold duration that has to be met, before the haptic and action are fired?

My current `items.json` is tiny, while I experiment with MTMR-
```
[{
	"type": "escape",
	"width": 900,
	"align": "center"
}]
```

**Comment by Kevin-Prichard** [comment]
Sometimes when I press and hold 'esc' for half a second or longer, it still doesn't send it to the foreground app.

How can I help debug this?

**Comment by Toxblh** [comment]
I'll try to investigate it.

**Comment by Toxblh** [comment]
@Kevin-Prichard Could you try with version 0.18.1?
